### DISCUSSION TITLE
Google engine, problems - Really need some help!

### DISCUSSION THREAD

**Discussion by Taxick** [searxng/searxng#1411] [Q&A]
Hi.

I need some help! I simply can't get Google: Videos, Music, and Files to work.

I have read all the bug reports about this error here: [LINK](https://github.com/searxng/searxng/issues?q=is%3Aissue+%22Bug%3A+google+engine%22+is%3Aclosed)

I have also read this [page](https://docs.searxng.org/src/searx.utils.html#searx.utils.match_language)

Here is my google part from my settings.yml

```
engines:

  - name: google
    engine: google
    use_mobile_ui: true

  - name: google images
    engine: google_images
    use_mobile_ui: true

  - name: google news
    engine: google_news
    use_mobile_ui: true

  - name: google videos
    engine: google_videos
    use_mobile_ui: true

  - name: google scholar
    engine: google_scholar
    use_mobile_ui: true

  - name: google play apps
    engine: google_play_apps
    use_mobile_ui: true

  - name: google play movies
    engine: xpath
    use_mobile_ui: true
    search_url: https://play.google.com/store/search?q={query}&c=movies
    results_xpath: '//div[@class="ImZGtf mpg5gc"]'
    title_xpath: './/div[@class="RZEgze"]//div[@class="kCSSQe"]//a'
    url_xpath: './/div[@class="RZEgze"]//div[@class="kCSSQe"]//a/@href'
    content_xpath: './/div[@class="kCSSQe"]'
    thumbnail_xpath: './/div[@class="uzcko"]/div/span[1]//img/@data-src'
    categories: videos
    shortcut: gpm
    disabled: true
    about:
      website: https://play.google.com/
      wikidata_id: Q79576
      official_api_documentation:
      use_official_api: false
      require_api_key: false
      results: HTML
```

**What a I'm doing wrong?**

My site: [wub10.futurenode.dk](https://www.wub10.futurenode.dk)
