### DISCUSSION TITLE
settings.yml file

### DISCUSSION THREAD

**Discussion by davemp1** [searxng/searxng#1520] [Q&A]
Hello,

I am very new to this and I looking for a bit of help.  I got my Searxng running but I updated my setting.yml file with  method: "GET" under the section server.  It didn't work anymore, but when I go to remove what I had done, Searxng no longer works.

This is my settings.yml code

```
# see https://docs.searxng.org/admin/engines/settings.html#use-default-settings
use_default_settings: true
server:
  # base_url is defined in the SEARXNG_BASE_URL environment variable, see .env and docker-compose.yml
  secret_key: ""  # change this!
  limiter: true  # can be disabled for a private instance
  image_proxy: true
  method: "GET"
ui:
  static_use_hash: true
redis:
  url: redis://redis:6379/0
```

I am also wondering if it is possible to change the logo across the top so I can put a different picture or no picture at all.

Thank you
