### DISCUSSION TITLE
I found a way (maybe) to get SearXNG working over Tor on Docker

### DISCUSSION THREAD

**Discussion by ghost** [searxng/searxng#1665] [Ideas]
After an exhausting research through the Web and trial-and-error, it seems that I found my way. I pulled the osminogin/tor-simple image and edited the docker-compose.yaml. Of course I tweaked the settings.yml as well.
Here is my docker-compose-yaml ( I am just self-hosting the instance on localhost):

```yaml
version: '3.7'

services:
 
 caddy:
    container_name: caddy
    image: caddy:2-alpine
    ports:
        - "80:80"
       - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy-data:/data:rw
      - caddy-config:/config:rw
    environment:
      - SEARXNG_HOSTNAME=${SEARXNG_HOSTNAME:-http://localhost:80}
      - SEARXNG_TLS=${LETSENCRYPT_EMAIL:-internal}
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
      - DAC_OVERRIDE
      
  redis:
    container_name: redis
    image: "redis:alpine"
    command: redis-server --save "" --appendonly "no"
    networks:
      - searxng
    tmpfs:
      - /var/lib/redis
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
      - DAC_OVERRIDE

  searxng:
    container_name: searxng
    image: searxng/searxng:latest
    networks:
       - searxng
    ports:
     - "127.0.0.1:8080:8080"
    volumes:
      - ./searxng:/etc/searxng:rw
    environment:
      - SEARXNG_BASE_URL=http://${SEARXNG_HOSTNAME:-localhost}/
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1" 
  tor:
    image: osminogin/tor-simple
    container_name: mytor
    restart: always
    networks:
       - searxng
    ports:
      - "127.0.0.1:9050:9050"
           
networks:
  searxng:
     driver: 
       ipam:
          default
```

And what I added in settings.yml:
```
outgoing:
   request_timeout: 10.0
   proxies:
      all://:
         - socks5h://mytor:9050
   using_tor_proxy: true
```

I am open to any opinion and suggestion to make this workaround as clean and healthy as possible. For example, "network_mode: host" in the caddy section leads to a bind fail for localhost:8080, so I had to delete the line and let docker create a default caddy network. However I don't really know what happens if caddy can't connect to the host.
