### DISCUSSION TITLE
Retry mechanism when multiple proxies are available

### DISCUSSION THREAD

**Discussion by extremelyonline** [searxng/searxng#2367] [Q&A]
Hi, would anyone please clarify the behavior of outgoing proxies?

According to the [doc](https://docs.searxng.org/admin/engines/settings.html#outgoing), [a retry mechanism](
https://github.com/searx/searx/issues/2439) was implemented in Searxng. I have set up some socks5 proxies. They're working as far as I can tell. However, may I ask the following questions? 

- When I get `google ( [Suspended: too many requests]`, does it mean that google has ban all my source ip+outgoing proxies?
- If I have one source ip+two proxies, is `retries 3` the best practice?

Here's my setup under outgoing. Thank you!

```
  retries: 3
  retry_on_http_error: true
  proxies:
    all://:
      - socks5://user:pw@proxyhost1:port
      - socks5://user:pw@proxyhost2:port
```
