### DISCUSSION TITLE
State of ebay engine/can't get it to work

### DISCUSSION THREAD

**Discussion by xieve** [searxng/searxng#2487] [Q&A]
Posting here since I'm assuming this is a user error:

I'm trying to configure ebay (and potentially any other shopping-oriented engine, but I couldn't find any other as of right now) for the shopping tab. Here's the relevant portion of my `settings.yml`:
```yml
engines:
  - name: ebay
    engine: ebay
    shortcut: ede
    base_url: "https://ebay.de"
    timeout: 8.0
    categories: shopping
outgoing:
  max_redirects: 30
```
I can display random items off of ebay with an empty query and only a slightly broken theme (`!ede`), but if I actually want to search anything (`!ede <anything>), I get no results and SearXNG logs this:
```Python
2023-06-04 09:57:50,598 WARNING:searx.engines.ebay: ErrorContext('searx/search/processors/online.py', 127, 'count_error(', None, '1 redirects, maximum: 0', ('200', 'OK', 'www.ebay.de')) True
```

I'm wondering: Is this user error? Why is this engine (along with others) not included in the standard config? Is there documentation somewhere on these engines? Is this engine abandoned? (last commit from over a year ago)

Edit: I just noticed that when I search for `!ede`, this appears in the log:
```Python
2023-06-04 10:03:13,086 WARNING:searx.engines.ebay: ErrorContext('searx/search/processors/online.py', 127, 'count_error(', None, '3 redirects, maximum: 0', ('200', 'OK', 'www.ebay.de')) True
```

Edit: Looking at ebay.py, I also wonder if it could be implemented via the xpath engine alone.
