### DISCUSSION TITLE
searxng looks quite weird, is my config correct?

### DISCUSSION THREAD

**Discussion by peterge1998** [searxng/searxng#2689] [Q&A] [answered]
![image](https://github.com/searxng/searxng/assets/47355238/93342f4b-552f-40b4-8bca-ccd5d51d19dc)
```

  searxng:
    container_name: searxng
    image: searxng/searxng:latest
    restart: unless-stopped
    networks:
      bookstack:
        ipv4_address: 172.20.0.140
    ports:
      - 8080:8080
    volumes:
      - /srv/docker/searxng:/etc/searxng
    environment:
      - BASE_URL=suche.peterge.de
      - INSTANCE_NAME=suche.peterge.de
```

```
cat /etc/nginx/sites-enabled/suche.peterge.de 

server {
    if ($host = suche.peterge.de) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

listen 80;
server_name blog.peterge.de;
return 301 https://$host$request_uri;

}
server {
listen 443 ssl;
listen [::]:443 ssl;
server_name suche.peterge.de;
ssl on;
    ssl_certificate /etc/letsencrypt/live/suche.peterge.de/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/suche.peterge.de/privkey.pem; # managed by Certbot
ssl_session_cache builtin:1000 shared:SSL:10m;
ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
ssl_ciphers HIGH:!aNULL:!MD5;
location / {
proxy_set_header Host $host;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $scheme;
proxy_read_timeout 90;
proxy_pass http://172.20.0.140:8080/;
proxy_redirect http://172.20.0.140:8080/ https://suche.peterge.de;
client_max_body_size 100m;
}
}

```
This is the compose i am using. The site looks quite weird, is my issue the compose or the nginx cfg for the reverse proxy?
