### DISCUSSION TITLE
OpenSearch not working

### DISCUSSION THREAD

**Discussion by JoshuaVandaele** [searxng/searxng#3143] [Q&A]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**

2024.1.19+047c7a7cf

**How did you install SearXNG?**

Using searxng-docker

**What happened?**

When I add SearXNG to Firefox using the "Add to SearXNG", I cannot actually use it for neither autocompletion or searching, because the URL is using `http` instead of `https` in `opensearch.xml`

**How To Reproduce**

Right click -> Add InstanceName -> Try to search
![image](https://github.com/searxng/searxng/assets/24195176/5fdd9191-d5d7-4cfe-820f-2581fad76ca6)

**Expected behavior**

Working search

**Screenshots & Logs**

301 Redirect from http to https when trying to search for something using the browser, which just puts me on the search page with no query:
![image](https://github.com/searxng/searxng/assets/24195176/54358cf5-23d1-4eb9-95fd-bb411d1054d6)

**Additional context**

This is my Docker compose (with the domain redacted for privacy)

```yml
version: '3'

networks:
  networks_reverse_proxy:
    external: true

services:
  searxng:
    image: searxng/searxng
    networks:
      - networks_reverse_proxy
    container_name: searxng
    environment:
      - INSTANCE_NAME=SearXNG
      - BASE_URL=https://my.domain.tld/searxng
      - SEARXNG_BASE_URL=https://my.domain.tld/searxng
    volumes:
      - ./config:/etc/searxng
    restart: always
```
