### DISCUSSION TITLE
KeyError: 'default_doi_resolver'

### DISCUSSION THREAD

**Discussion by StephenJose-Dai** [searxng/searxng#3242] [Q&A]
I run the command python webapp.py and it started. I tried to access http://abc.com:8888, but an error seemed to be reported.

I don't even know why it happens.

What can I do to get it to work properly?

i use Step-by-step installation

![image](https://github.com/searxng/searxng/assets/36736149/1dcd9d3d-f3b0-406b-9cad-10c4f0368823)

![image](https://github.com/searxng/searxng/assets/36736149/d908c2c8-8c78-4b00-95a9-6a30c50c5519)

**Comment by procoprobocop** [comment]
After configuring the console.yml offers the following actions:
```
doi_resolvers:
  oadoi.org: 'https://oadoi.org/'
  doi.org: 'https://doi.org/'
  doai.io: 'https://dissem.in/'
  sci-hub.se: 'https://sci-hub.se/'
  sci-hub.st: 'https://sci-hub.st/'
  sci-hub.ru: 'https://sci-hub.ru/'

default_doi_resolver: 'oadoi.org'
```
