### DISCUSSION TITLE
not returning json results, only html

### DISCUSSION THREAD

**Discussion by im-fabian** [searxng/searxng#3542] [Q&A] [answered]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
2024.5.31+18fb701be (via docker)

**How did you install SearXNG?**
Via docker-compose:

```
  searxng:
    image: docker.io/searxng/searxng:latest
    container_name: searxng
    ports:
      - "127.0.0.1:8080:8080"
    networks:
     - internal_network
     - public_network
    environment:
     - SEARXNG_BASE_URL=http://searxng:8080
     - INSTANCE_NAME=HuggingSearch
    volumes:
     - /opt/hugging-chat/data/searxng:/etc/searxng
    cap_drop:
     - ALL
    cap_add:
     - CHOWN
     - SETGID
     - SETUID
```

**What happened?**
curl http://127.0.0.1:8080/search?q=test&engines=duckduckgo&format=json returns html results not json.

**How To Reproduce**
Setup searxng via docker compose. 
Enable json within settings.yml (search: formats: - json), restart docker container. Try to get json results via curl. 

**Expected behavior**
Should get results as json.

**Screenshots & Logs**

**Additional context**

**Comment by return42** [comment]
If you test with a `make run` instance you see json output will work, not sure if you have issues related to [searxng-docker (Discussions)](https://github.com/searxng/searxng-docker/discussions) / please don't open a bug report if you have questions; we have a Q&A section in the "Discussion" .. further we have a really active and help full community at [#searxng:matrix.org](https://matrix.to/#/#searxng:matrix.org) .. I recommend you to ask & discuss questions there.

I'm going to close this "bug report".

**Comment by xellaren** [comment]
For me it fixed after set formats in config to all allowed in array way:
```
  # remove format to deny access, use lower case.
  # formats: [html, csv, json, rss]
  formats:
    [html, csv, json, rss]
```

Also i had a VPN connected, seems it interfered.

**Comment by emuchogu** [comment, marked as answer]
Do the following to enable the api:

1. Edit the settings file:
```bash
vi searxng/settings.yml
```

2. Add 'json' to the formats section:
```yaml
search:
  formats:
    - html
    - json
```

3. Restart the container to apply changes:
```bash
docker restart searxng
```

The API should now respond to JSON format requests.
