### DISCUSSION TITLE
No border and transparent background for favicons

### DISCUSSION THREAD

**Discussion by Nordlicht-13** [searxng/searxng#4023] [Q&A] [answered]
Is there a way to get rid of the border and the gray background of the favicons?
I would like tho have the plain icon without the gray background and boarder
like e.g. at the search-results of duckduckgo.

**Comment by return42** [comment, marked as answer]
There is not option to modify the visual of the favicons.

> like e.g. at the search-results of duckduckgo.

We already discussed it, here is a screenshot from ddg .. black logo on transparent (dark) background:

![grafik](https://github.com/user-attachments/assets/182df776-e239-4e0e-a6c7-356051d24dde)

And here and here in this comment a comparison:

- https://github.com/searxng/searxng/pull/3945#issuecomment-2423697173

**Reply by szotsaki** [reply]
I understand that on black background you would like to keep this way, but why not modify on the default light background?

The browsers nowadays are capable of [conditionally applying colours](https://developer.mozilla.org/en-US/docs/Web/CSS/Reference/Values/color_value/light-dark) based on colour scheme.

The only modification I needed to make was:

```css
.favicon img {
    background-color: light-dark(transparent, var(--color-favicon-background-color));
    border-color: light-dark(transparent, var(--color-favicon-border-color));
    width: 1.1rem;
    height: 1.1rem;
}

.result .url_header {
    gap: .3rem;
}
```

This is how it looks like in the current version:
<img width="830" height="1026" alt="image" src="https://github.com/user-attachments/assets/7155a710-547f-4293-8879-c86d5e9e6698" />

And this is without gray background and border, 1.1 rem width/height, and 0.3 rem gap:
<img width="812" height="1037" alt="image" src="https://github.com/user-attachments/assets/aebdc65a-3730-4be2-905e-1e51a7ea481a" />
