### DISCUSSION TITLE
Unable to install

### DISCUSSION THREAD

**Discussion by back-lacking** [searxng/searxng#4238] [Q&A] [answered]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Using https://github.com/searxng/searxng
version `2025.1.25+176079977`
-->
**How did you install SearXNG?**
installed via Docker-compose. redis container is in a seperate compose file and is being used by other containers + searxng
```yaml
version: "3.7"
services:
  searxng:
    container_name: searxng
    hostname: searxng
    image: searxng/searxng:latest
    networks:
      - searxng
      - proxy
    volumes:
      - ./searxng:/etc/searxng:rw
    environment:
      - SEARXNG_BASE_URL=https://${SEARXNG_HOSTNAME:-localhost}/
    labels:
      - traefik.enable=true
      - traefik.http.routers.searxng.entrypoints=web
      - traefik.http.routers.searxng.rule=Host(`search.local.domain`)
      - traefik.http.middlewares.searxng-https-redirect.redirectscheme.scheme=websecure
      - traefik.http.routers.searxng.middlewares=searxng-https-redirect
      - traefik.http.routers.searxng-secure.entrypoints=websecure
      - traefik.http.routers.searxng-secure.rule=Host(`search.local.domain`)
      - traefik.http.routers.searxng-secure.tls=true
      - traefik.http.routers.searxng-secure.service=searxng
      - traefik.http.services.searxng.loadbalancer.server.port=8080
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    logging:
      driver: json-file
      options:
        max-size: 1m
        max-file: "1"
networks:
  searxng: null
  proxy:
    external: true
```

**What happened?**
I dont really know what happened. one minute i was able to search things up completely fine, the next minute, i was unable to search things up and would constantly get time outs on all engines. there was no changes in my configurations aside from a domain change but even then it still worked completely fine up until now
**How To Reproduce**
Honestly i dont even know how to reproduce this

**Expected behavior**
it would search things up and give results
**Screenshots & Logs**
https://pastebin.com/HF8Ch2Mp last 300 lines pulled from the searxng container via portainer

**Additional context**
