### DISCUSSION TITLE
[Bug] Hostnames plugin not working at all

### DISCUSSION THREAD

**Discussion by sicusa** [searxng/searxng#4261] [Q&A] [answered]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
2025.1.29+738906358

**How did you install SearXNG?**
using searxng-docker

**What happened?**
settings.yml:
```yaml
...
enabled_plugins:
  - 'Basic Calculator'
  - 'Hash plugin'
  - 'Self Information'
  - 'Tracker URL remover'
  - 'Unit converter plugin'
  - 'Ahmia blacklist'  # activation depends on outgoing.using_tor_proxy
  - 'Hostnames plugin'  # see 'hostnames' configuration below
  - 'Open Access DOI rewrite'

hostnames:
  remove:
    - '(.*\.)?microsoft.com$'
...
```

**Screenshots & Logs**
Still got results from microsoft.com:
<img width="1210" alt="Image" src="https://github.com/user-attachments/assets/860376b1-9877-4b23-b9bb-72020e792d30" />
