### DISCUSSION TITLE
Autocomplete only partially working

### DISCUSSION THREAD

**Discussion by Azmodeszer** [searxng/searxng#4262] [Q&A] [answered]
I found a few issues here referencing this, but none of the solutions did the trick for me.

I have a self-hosted instance deployed via docker-compose/Portainer stack. Everything seems to work fine, except for autocomplete. When I type something in the instance's search bar itself, it works, but when I use my browser's (Firefox) address bar, it does not. I have successfully configured searXNG as my default search engine in Firefox and `https://myinstance.com/autocompleter?q=word` returns a valid JSON with suggestions. duckduckgo is also set in my searXNG's settings to use for autocomplete.

The stack I deployed:
```
services:
  redis:
    container_name: redis
    image: docker.io/valkey/valkey:8-alpine
    command: valkey-server --save 30 1 --loglevel warning
    restart: unless-stopped
    networks:
      - searxng
    volumes:
      - valkey-data2:/data
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

  searxng:
    container_name: searxng
    image: docker.io/searxng/searxng:latest
    restart: unless-stopped
    networks:
      - searxng
    ports:
      - "8282:8080"
    volumes:
      - ./searxng:/etc/searxng:rw
      - /home/azmodes/searxng/favicons.toml:/usr/local/searxng/searx/favicons/favicons.toml #same here, without this no list of resolvers to select from would show up
    environment:
      - SEARXNG_BASE_URL=https://myinstance.com/
      - UWSGI_WORKERS=${SEARXNG_UWSGI_WORKERS:-4}
      - UWSGI_THREADS=${SEARXNG_UWSGI_THREADS:-4}
      - AUTOCOMPLETE=duckduckgo
    #  - SEARXNG_LIMITER=true
    #  - SEARXNG_PUBLIC_INSTANCE=true
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

networks:
  searxng:

volumes:
  valkey-data2:
```

I'm a bit of a noob with docker/compose, so maybe some of the adjustments here are to blame.

Thanks.

**Comment by return42** [comment]
In ["How do I set it as the default search engine?"](https://docs.searxng.org/user/about.html#how-do-i-set-it-as-the-default-search-engine) look out for "OpenSearch" and "firefox" .. fruther related: ["which (mobile) browsers support OpenSearch?"](https://github.com/searxng/searxng/issues/431)

**Reply by Azmodeszer** [reply]
Sorry, but I don't really see anything pertaining to my problem in these links. As I said, I have already set up searXNG as the default search engine for Firefox and it works. The issue is that autocomplete refuses to work if I use the browser address bar.

**Reply by return42** [reply]
> but when I use my browser's (Firefox) address bar, it does not. I

...

>> In ["How do I set it as the default search engine?"](https://docs.searxng.org/user/about.html#how-do-i-set-it-as-the-default-search-engine) look out for "OpenSearch" and "firefox" .. fruther related: ["which (mobile) browsers support OpenSearch?"](https://github.com/searxng/searxng/issues/431)

...

> Sorry, but I don't really see anything pertaining to my problem in these links

...

Ask yourself how you have added SearXNG to the search engines in FFox.

**Reply by Azmodeszer** [reply]
From the address bar, as described [here](https://support.mozilla.org/en-US/kb/add-or-remove-search-engine-firefox).

**Reply by return42** [reply, marked as answer]
> From the address bar, as described [here](https://support.mozilla.org/en-US/kb/add-or-remove-search-engine-firefox).

Ah, OK .. that's fine .. now I remember, there is an HTTP-POST issue with the search from URL bar:

I assume you activated HTTP-POST in the preferences or the SearXNG instance you use has HTTP-POST by default ..  most instances have POST as default 


https://github.com/searxng/searxng/blob/738906358bf679dcaef3584fd48bf138e3671397/searx/settings.yml#L103-L105

Related:

- [While autocompletion in the search field of SearXNG sends a cookie, the autocompletion in the URL bar does not send a cookie.](https://github.com/searxng/searxng/issues/1889#issuecomment-1565366772)
- https://github.com/searxng/searxng/pull/2333#issuecomment-1565392120
- [POST vs GET --> some broswers don't like HTTP POST requests in a OpenSearch query ](https://github.com/searxng/searxng/issues/431)

due to all these issues and quirks of HTTP POST I decided to activated HTTP-GET on my instance by default.

```yaml
server:
  method: GET

preferences:
  lock:
    - method
```

and I locked the `method` in the preferences / so user can't switch to HTTP POST .. where all the trouble finds it starting point ;-)
