### DISCUSSION TITLE
How to allow the search engine redirection of searxng?

### DISCUSSION THREAD

**Discussion by ffyuhf** [searxng/searxng#4329] [Q&A] [answered]
I am in China, the default search engine enabled by searxng is not available here, the only available search engine Bing redirects to cn.bing.com, so I would like to adjust the number of redirects for the search engine (the default is zero) to allow redirection. I am using Docker for deployment, what should I do?😥

**Comment by dalf** [comment, marked as answer]
You can change the URL for the bing:
https://github.com/searxng/searxng/blob/d456f3dd9fb97bcc4e8695b36e9522250f596ac2/searx/engines/bing.py#L70

In `searxng/settings.yml`:

```yaml
use_default_settings: true
...
engines:
  - name: bing
    engine: bing
    base_url: "https://cn.bing.com/search"
```

this should work as long as the HTML layout is identical.


(I can't find the right parameter for the number of redirect: max_redirect  is [set to 30 by default](https://github.com/searxng/searxng/blob/d456f3dd9fb97bcc4e8695b36e9522250f596ac2/searx/settings_defaults.py#L224))
