### DISCUSSION TITLE
Soft fail?

### DISCUSSION THREAD

**Discussion by s7x** [searxng/searxng#4438] [Q&A]
Hi there!

I was wondering if there's any way to enable a "soft fail" for the private instances. I'm running multiple engines and some requests are giving me a hard fail without any results (but I do have results in reality for example here with startpage).

![image](https://github.com/user-attachments/assets/52e7075c-4f61-4f2e-931c-11a3dc9c47b0)

My question is: do we have a sort of "soft fail" mechanism that just shows the available results?

Thanks!

Configuration of the settings.yml:

```yaml
use_default_settings: true

search:
  safe_search: 0
  favicon_resolver: "duckduckgo"
  default_lang: "en"

server:
  secret_key: "REDACTED"
  limiter: true
  image_proxy: true
  http_protocol_version: "1.1"

checker:
  scheduling:
  start_after: [300, 1800]  # delay to start the first run of the checker
  every: [86400, 90000]     # how often the checker runs

engines:
  - name: annas archive
    disabled: false
  - name: bing
    disabled: false
  - name: bitbucket
    disabled: false
  - name: brave
    disabled: false
  - name: crowdview
    disabled: false
  - name: duckduckgo
    disabled: false
  - name: duckduckgo images
    diabled: false
  - name: duckduckgo videos
    disabled: false
  - name: gitlab
    disabled: false
  - name: qwant
    disabled: true
  - name: startpage
    disabled: false
  - name: tineye
    diabled: false
  - name: wikipedia
    disabled: true

  # Translate
  - name: dictzone
    disabled: true
  - name: lingva
    disabled: true
  - name: mymemory translated
    disabled: true

general:
  instance_name: "SearXNG"
  enable_metrics: false

ui:
  static_use_hash: true
  theme_args:
    simple_style: "dark"
```
