### DISCUSSION TITLE
json_engine content_query concatenation

### DISCUSSION THREAD

**Discussion by grasdk** [searxng/searxng#4569] [Q&A] [answered]
Hi

I'm trying to create a search engine for my local portainer, just as an experiment. It works, but I'm missing how to concatenate multiple parts of the output into the content result for searxng.

Can this be done?

Here's my engine:

```
  - name: portainer
    engine: json_engine
    paging: False
    enable_http: True
    headers:
      X-Api-Key: <secret>
    search_url: http://myportianer/api/endpoints/1/docker/containers/json?filters%3D%7B%22name%22%3A%5B%22{query}%22%5D%7D
#    results_query: #root
    url_query: Image
    title_query: Names/0
    content_query: Mounts/1/Source
    content_html_to_text: false
    shortcut: port
    timeout: 5.0
```

I would like to show much more in the searxng result content than just the first mount source. Namely multiple mounts with their type, source and destination. Also network information and other info. 

But let's keep it simple... Can I add `Mounts/1/Destination` to the output?

Here is some partial output from Portainer:

```
"Mounts":[
  {
    "Destination":"/etc/searxng", 
    "Mode":"rw",
    "Propagation":"rprivate",
    "RW":true,
    "Source":"/host/path/to/searxng",
    "Type":"bind"
  }
]
```

Thank you for any help or clarification.
