### DISCUSSION TITLE
Adding include capabilities to settings.yml

### DISCUSSION THREAD

**Discussion by grasdk** [searxng/searxng#4638] [Ideas]
I'm a newcomer to searxng, but I like it a lot and love the customizability. I deploy searxng using docker and have my personal `settings.yml` in a volume, so I have the configuration seperately.

One thing that surprised me is that `settings.yml` is quite large and in a certain sense "monolithic" in an otherwise very modular setup.

A possible solution would be to add "include" capability to `settings.yml`, maybe even with extended capabilities for including a folder (with yml-files in it).

As I have been working only with custom search engines, this is my focus, but it would probably be beneficial to other parts of `settings.yml` as well.

Example of the idea

```
engines:
!include /usr/local/share/searxng/custom_engines/

  - name: 360search
    engine: 360search
    shortcut: 360so
    disabled: true
    
    ... (and the rest of the default engines - or they may be in a folder by themselves)
``` 

the folder with engine definitions could simply contain just the engine definitions
```
$ls /usr/local/share/searxng/custom_engines/
engine_mywiki.yml  engine_image_database.yml  engine_my_docs.yml
```

Looks like there is a python framework for it already: https://stackoverflow.com/questions/528281/how-can-i-include-a-yaml-file-inside-another

I might dive into this myself at some point if someone else doesn't beat me to it, or argue why it's a bad idea here.
