### DISCUSSION TITLE
Enabling `using_tor_proxy` causes `Internal Server Error`.

### DISCUSSION THREAD

**Discussion by Dunkmania101** [searxng/searxng#4715] [Q&A]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**

SearXNG version: 2025.5.3-8ef5fbca4
tor-simple version: 0.4.8.16

**How did you install SearXNG?**

docker-compose.yml:
```
services:
  tor-1:
    image: osminogin/tor-simple
    restart: unless-stopped
  searxng-1:
    container_name: searxng-1
    image: searxng/searxng:latest
    depends_on:
      - tor-1
    restart: unless-stopped
    ports:
      - "8888:8080"
    environment:
      BASE_URL: "http://localhost:8888"
    volumes:
      - "$HOME/ProgramFiles/searxng/config:/etc/searxng"
```

Then:
docker compose -f ~/ProgramFiles/searxng/docker-compose.yml up -d --pull always

Outgoing section of settings.yml:
```
outgoing:
  # default timeout in seconds, can be override by engine
  request_timeout: 3.0
  # the maximum timeout in seconds
  # max_request_timeout: 10.0
  # suffix of searx_useragent, could contain information like an email address
  # to the administrator
  useragent_suffix: ""
  # The maximum number of concurrent connections that may be established.
  pool_connections: 100
  # Allow the connection pool to maintain keep-alive connections below this
  # point.
  pool_maxsize: 20
  # See https://www.python-httpx.org/http2/
  enable_http2: true
  # uncomment below section if you want to use a custom server certificate
  # see https://www.python-httpx.org/advanced/#changing-the-verification-defaults
  # and https://www.python-httpx.org/compatibility/#ssl-configuration
  #  verify: ~/.mitmproxy/mitmproxy-ca-cert.cer
  #
  # uncomment below section if you want to use a proxyq see: SOCKS proxies
  #   https://2.python-requests.org/en/latest/user/advanced/#proxies
  # are also supported: see
  #   https://2.python-requests.org/en/latest/user/advanced/#socks
  #
  proxies:
    all://:
      - socks5h://tor-1:9050

  using_tor_proxy: true

  #Extra seconds to add in order to account for the time taken by the proxy

  extra_proxy_timeout: 10
```

**What happened?**

Upon attempting to run a search with the above configuration (namely using_tor_proxy set to true), an `Internal Server Error` page is returned. Occasionally, localhost:$PORT (no query) will load successfully with using_tor_proxy enabled and then performing a query with the search bar will load the internal server page. If using_tor_proxy is false but the tor proxy is still configured, the search engine functions normally with the exception of frequent proxy errors, some of which may simply be due to engines refusing to respond over tor. I do suspect that some errors may be resolved by enabling using_tor_proxy (provided it works at all), but I haven't been able to test that because of the internal server errors.

**How To Reproduce**

Install and configure SearXNG as described above (Docker and Podman yield the same result) and attempt to run a search.

**Expected behavior**

Upon attempting a search with a tor proxy configured and using_tor_proxy, a results page should load successfully, albeit with the possibility that some 3rd party engines may refuse to respond.

**Screenshots & Logs**

Here is a tail of the output of `docker logs searxng-1`:

[searxng_log.txt](https://github.com/user-attachments/files/20025299/searxng_log.txt)

It does seem to mention some tor proxy errors and refers to pertinent source files.

**Additional context**

I'm not entirely certain if this is the exact thread, but I believe it is what I based my proxy configuration on:
https://github.com/searxng/searxng/discussions/1665
