### DISCUSSION TITLE
[question] recommendations for an invidious setup

### DISCUSSION THREAD

**Discussion by return42** [searxng/searxng#911] [Q&A]
I open this issue to exchange invidious experience / not to say I have zero experience :-)

In the SearXNG default setup we have ..

https://github.com/searxng/searxng/blob/81453a0ebab2b4b041828efc3653576f909d2768/searx/settings.yml#L778-L785

- My experience is, that a timeout of 5 sec is not need, I got fast response >1sec on my instance.
- Do you recommend different `base_url` .. is your recommendation related to the continent where the instance is hosted or to the location where the majority of your users are from?

Do you redirect (replace hostname / [further see](https://github.com/searxng/searxng/issues/725)) youtube links to invidious?

https://github.com/searxng/searxng/blob/81453a0ebab2b4b041828efc3653576f909d2768/searx/settings.yml#L177-L179 

Do you miss any feature in our [invidious engine](https://github.com/searxng/searxng/blob/master/searx/engines/invidious.py) or do you have suggestion for improvements?

----

Here are my `/etc/searxng/settings.yml` settings (EDIT no longer needed, already added to the sources 10c9b9775):

```yaml
  - name: invidious
    engine: invidious
    # Instances will be selected randomly, see https://api.invidious.io/ for
    # instances that are stable (good uptime) and close to you.
    base_url:
      - https://invidious.snopyta.org
      - https://vid.puffyan.us
      - https://invidious.kavin.rocks
      - https://invidio.xamh.de
      - https://inv.riverside.rocks
    shortcut: iv
    timeout: 3.0
    disabled: true
```

The instances are used [randomly](https://github.com/searxng/searxng/pull/867), but all results (incl. youtube) are redirected to an instance in DE where the majority of my users is located:

```yaml
hostname_replace:

  # youtube --> Invidious

  '(.*\.)?youtube\.com$': 'invidio.xamh.de'
  '(.*\.)?invidious\.snopyta\.org$': 'invidio.xamh.de'
  '(.*\.)?vid\.puffyan\.us': 'invidio.xamh.de'
  '(.*\.)?invidious\.kavin\.rocks$': 'invidio.xamh.de'
  '(.*\.)?inv\.riverside\.rocks$': 'invidio.xamh.de'
```
