### DISCUSSION TITLE
Content-Security-Policy & privacy redirects

### DISCUSSION THREAD

**Discussion by return42** [searxng/searxng#918] [Q&A]
For know-how exchange about CSP .. comments are welcome

Below you find my CSP entries in `seetings.yml`

```yaml

server:
  ...
  default_http_headers:
    ...
    Content-Security-Policy: >-
      default-src 'self' data
      https://invidio.xamh.de
      https://mp-tube.de
      https://cdn-storage.br.de
      https://*.akamaihd.net
      https://player.vimeo.com
      https://www.mixcloud.com
      https://w.soundcloud.com
      https://www.dailymotion.com
      https://www.deezer.com
      https://genius.com
      https://apasfiis.sf.apa.at
      https://media.tagesschau.de
      ;
      img-src 'self' data:
      https://*.tile.openstreetmap.org
      https://maps.wikimedia.org
      ;
```

My user base is located in DE, I redirected youtube and invidios URLs to `invidio.xamh.de`, thats why I don't need youtube in my CSP header. 

```yaml

enabled_plugins:
  # these plugins are enabled if nothing is configured ..
  - 'Hash plugin'
  - 'Search on category select'
  - 'Self Informations'
  - 'Tracker URL remover'
  - 'Ahmia blacklist'  # activation depends on outgoing.using_tor_proxy
  # these plugins are disabled if nothing is configured ..
  - 'Hostname replace'  # see hostname_replace configuration below
  # - 'Infinite scroll'
  # - 'Open Access DOI rewrite'
  # - 'Vim-like hotkeys'

hostname_replace:

  # youtube --> Invidious

  '(.*\.)?youtube\.com$': 'invidio.xamh.de'
  '(.*\.)?youtube-nocookie\.com$': 'invidio.xamh.de'
  '(.*\.)?invidious\.snopyta\.org$': 'invidio.xamh.de'
  '(.*\.)?exo\.tube$': 'invidio.xamh.de'
  '(.*\.)?vid\.puffyan\.us': 'invidio.xamh.de'
  '(.*\.)?tube\.darknight-coffee\.org': 'invidio.xamh.de'
  '(.*\.)?socialwebtube\.com': 'invidio.xamh.de'
  '(.*\.)?invidious\.kavin\.rocks$': 'invidio.xamh.de'
  '(.*\.)?inv\.riverside\.rocks$': 'invidio.xamh.de'
  '(.*\.)?peertube\.togart\.de$': 'invidio.xamh.de'

  # twitter --> nitter

  '(www\.)?twitter\.com$': 'nitter.net'
```

----

Related: https://github.com/searxng/searxng/discussions/911
