### DISCUSSION TITLE
[question] hostname plugin: what results do you ignore?

### DISCUSSION THREAD

**Discussion by return42** [searxng/searxng#970] [Q&A]
FYI: the old `hostname_replace` plugin has been superseded by the `hostnames` plugin:

- https://github.com/searxng/searxng/pull/3463

------------

I open this issue to share some experience about results (domains) that can be ignored.

For reference: collected lists

- https://github.com/stroobants-dev/ublock-origin-shitty-copies-filter
- https://github.com/jhchabran/code-search-blacklist  (see [comment](https://github.com/searxng/searxng/issues/725#issuecomment-1008196147))

------

Updated 17/12/2024: Here is my current [`hostnames:`](https://docs.searxng.org/src/searx.plugins.hostnames.html) setup:

```yaml

hostnames:

  replace:
    # twitter --> nitter
    '(www\.)?twitter\.com$': 'nitter.net'

  remove:

    # block bload domains

    - 'com\.de'
    - '(.*\.)?askinglot\.com'
    - '(.*\.)?flipboard\.com'

    - '(.*\.)?codegrepper\.com'
    - '(.*\.)?w3schools\.com'
    - '(.*\.)?geeksforgeeks\.org'
    - '(.*\.)?stackshare\.io'
    - '(.*\.)?tutorialspoint\.com'
    - '(.*\.)?answeright\.com'
    - '(.*\.)?askdev\.info'
    - '(.*\.)?askdev\.io'
    - '(.*\.)?blogmepost\.com'
    - '(.*\.)?c-sharpcorner\.com'
    - '(.*\.)?code-examples\.net'
    - '(.*\.)?codeflow\.site'
    - '(.*\.)?gitmemory\.cn'
    - '(.*\.)?gitmemory\.com'
    - '(.*\.)?intellipaat\.com'
    - '(.*\.)?javaer101\.com'
    - '(.*\.)?programmerstart\.com'
    - '(.*\.)?programmersought\.com'
    - '(.*\.)?qastack\.com'
    - '(.*\.)?roboflow\.ai'
    - '(.*\.)?stackanswers\.net'
    - '(.*\.)?stackoom\.com'
    - '(.*\.)?stackovernet\.com'
    - '(.*\.)?stackovernet\.xyz'
    - '(.*\.)?stackoverrun\.com'
    - '(.*\.)?thetopsites\.net'
    - '(.*\.)?ubuntugeeks\.com'
    - '(.*\.)?cyberciti\.biz'
    - '(.*\.)?ispycode\.com'
    - '(.*\.)?reposhub\.com'
    - '(.*\.)?githubmemory\.com'
    - '(.*\.)?issueexplorer\.com'
    - '(.*\.)?tabnine\.com'
    - '(.*\.)?gitcode\.net'
    - '(.*\.)?command-not-found\.com'
    - '(.*\.)?im-coder\.com'
    - '(.*\.)?i-harness\.com'

    # ublock-origin-shitty-copies-filter/stackoverflow-copycats.txt

    - '(.*\.)?code-examples\.net'
    - '(.*\.)?kotaeta\.com'
    - '(.*\.)?answer-id\.com'
    - '(.*\.)?code\.i-harness\.com'
    - '(.*\.)?living-sun\.com'
    - '(.*\.)?qastack\.jp'
    - '(.*\.)?qastack\.ru'
    - '(.*\.)?qastack\.it'
    - '(.*\.)?qastack\.mx'
    - '(.*\.)?qastack\.com\.br'
    - '(.*\.)?qastack\.info\.tr'
    - '(.*\.)?qastack\.in\.th'
    - '(.*\.)?qastack\.com\.de'
    - '(.*\.)?qastack\.fr'
    - '(.*\.)?qastack\.cn'
    - '(.*\.)?qastack\.com\.ua'
    - '(.*\.)?qastack\.co\.in'
    - '(.*\.)?qastack\.kr'
    - '(.*\.)?qastack\.vn'
    - '(.*\.)?qastack\.net\.bd'
    - '(.*\.)?qa-stack\.pl'
    - '(.*\.)?qastack\.id'
    - '(.*\.)?coder\.work'
    - '(.*\.)?it-swarm-ja\.tech'
    - '(.*\.)?it-swarm\.jp\.net'
    - '(.*\.)?it-mure\.jp\.net'
    - '(.*\.)?it-swarm-ja\.com'
    - '(.*\.)?it-swarm\.com\.ru'
    - '(.*\.)?codeflow\.site'
    - '(.*\.)?codeguides\.site'
    - '(.*\.)?overcoder\.net'
    - '(.*\.)?coderoad\.ru'
    - '(.*\.)?generacodice\.blog'
    - '(.*\.)?generacodice\.it'
    - '(.*\.)?generacodice\.com'
    - '(.*\.)?javaer101\.com'
    - '(.*\.)?voidcc\.com'
    - '(.*\.)?siwib\.org'
    - '(.*\.)?fluffyfables\.com'
    - '(.*\.)?fixes\.pub'
    - '(.*\.)?knews\.vip'
    - '(.*\.)?isolution\.pro'
    - '(.*\.)?uwenku\.com'
    - '(.*\.)?lycaeum\.dev'
    - '(.*\.)?brocante\.dev'
    - '(.*\.)?classmethod\.dev'
    - '(.*\.)?stormcrow\.dev'
    - '(.*\.)?athabasca-foto\.com'
    - '(.*\.)?zsharp\.org'
    - '(.*\.)?projectbackpack\.org'
    - '(.*\.)?waymanamechurch\.org'
    - '(.*\.)?sunflowercreations\.org'
    - '(.*\.)?cfadnc\.org'
    - '(.*\.)?fitforlearning\.org'
    - '(.*\.)?panaindustrial\.com'
    - '(.*\.)?sierrasummit2005\.org'
    - '(.*\.)?theshuggahpies\.com'
    - '(.*\.)?pcbconline\.org'
    - '(.*\.)?nuomiphp\.com'
    - '(.*\.)?ubuntu\.buildwebhost\.com'
    - '(.*\.)?ubuntuaa\.com'
    - '(.*\.)?debugcn\.com'
    - '(.*\.)?sch22\.org'
    - '(.*\.)?gupgallery\.com'
    - '(.*\.)?amuddycup\.com'
    - '(.*\.)?ecnf2016\.org'
    - '(.*\.)?softwareuser\.asklobster\.com'
    - '(.*\.)?domainelespailles\.net'
    - '(.*\.)?ec-europe\.org'
    - '(.*\.)?pakostnici\.com'
    - '(.*\.)?try2explore\.com'
    - '(.*\.)?laravelquestions\.com'
    - '(.*\.)?itectec\.com'
    - '(.*\.)?stackovergo\.com'
    - '(.*\.)?faithcov\.org'
    - '(.*\.)?noblenaz\.org'
    - '(.*\.)?py4u\.net'
    - '(.*\.)?culinarydegree\.info'
    - '(.*\.)?safehavenpetrescue\.org'
    - '(.*\.)?qapicks\.com'
    - '(.*\.)?issues-world\.com'
    - '(.*\.)?narkive\.jp'
    - '(.*\.)?ourladylakes\.org'
    - '(.*\.)?intellipaat\.com'
    - '(.*\.)?article\.docway\.net'
    - '(.*\.)?xiu2\.net'
    - '(.*\.)?codehero\.jp'
    - '(.*\.)?quabr\.com'
    - '(.*\.)?webdevqa\.jp\.net'
    - '(.*\.)?qapicks\.com'
    - '(.*\.)?exceptionshub\.com'
    - '(.*\.)?newbedev\.com'
    - '(.*\.)?codenong\.com'
    - '(.*\.)?cainiaojiaocheng\.com'
    - '(.*\.)?routinepanic\.com'
    - '(.*\.)?pythonwd\.com'
    - '(.*\.)?tutorialmore\.com'
    - '(.*\.)?alwaysemmyhope\.com'
    - '(.*\.)?pretagteam\.com'
    - '(.*\.)?titanwolf\.org'
    - '(.*\.)?coderedirect\.com'
    - '(.*\.)?ostack\.cn'
    - '(.*\.)?easysavecode\.com'
    - '(.*\.)?webdevdesigner\.com'
    - '(.*\.)?ghcc\.net'
    - '(.*\.)?developreference\.com'
    - '(.*\.)?semicolonworld\.com'
    - '(.*\.)?tipsfordev\.com'
    - '(.*\.)?qi-u\.com'
    - '(.*\.)?stackqna\.com'
    - '(.*\.)?xsprogram\.com'
    - '(.*\.)?stackoom\.com'
    - '(.*\.)?it-swarm-fr\.com'
    - '(.*\.)?imtqy\.com'
    - '(.*\.)?christfever\.in'
    - '(.*\.)?codersatellite\.com'
    - '(.*\.)?cndgn\.com'
    - '(.*\.)?coredump\.biz'
    - '(.*\.)?farath\.com'
    - '(.*\.)?devbugfix\.com'
    - '(.*\.)?tech\.wayne-chu\.com'
    - '(.*\.)?stackify\.dev'
    - '(.*\.)?webknox\.com'
    - '(.*\.)?stackfinder\.jp\.net'
    - '(.*\.)?coder-solution-jp\.com'
    - '(.*\.)?jpndev\.com'
    - '(.*\.)?uebu-kaihatsu\.jp\.net'
    - '(.*\.)?sqlite\.in'
    - '(.*\.)?stackguides\.com'
    - '(.*\.)?younggeeks\.in'
    - '(.*\.)?answerlib\.com'
    - '(.*\.)?edupro\.id'
    - '(.*\.)?python-stack\.de'
    - '(.*\.)?stackfinder\.ru'
    - '(.*\.)?stackfault\.net'
    - '(.*\.)?howtofix\.io'
    - '(.*\.)?buzzphp\.com'
    - '(.*\.)?desenv-web-rp\.com'
    - '(.*\.)?askdev\.vn'
    - '(.*\.)?quares\.ru'
    - '(.*\.)?examplefiles\.net'
    - '(.*\.)?codewdw\.com'
    - '(.*\.)?jpcodeqa\.com'
    - '(.*\.)?tutorialguruji\.com'

     # ublock-origin-shitty-copies-filter/github-copycats.txt

    - '(.*\.)?bleepcoder.com'
    - '(.*\.)?githubja.com'
    - '(.*\.)?gitmemory.com'
    - '(.*\.)?giters.com'
    - '(.*\.)?githubmemory.com'
    - '(.*\.)?wenyanet.com'
    - '(.*\.)?issueexplorer.com'
    - '(.*\.)?opensourcelibs.com'
    - '(.*\.)?awesomeopensource.com'
    - '(.*\.)?findbestopensource.com'
    - '(.*\.)?githubhelp.com'
    - '(.*\.)?pythonissues.com'
    - '(.*\.)?golangrepo.com'
    - '(.*\.)?gitmemory.cn'
    - '(.*\.)?githubmate.com'
    - '(.*\.)?reposhub.com'
    - '(.*\.)?gitanswer.com'
    - '(.*\.)?githubplus.com'
    - '(.*\.)?pythonrepo.com'
    - '(.*\.)?bestofcpp.com'
    - '(.*\.)?github.innominds.com'
    - '(.*\.)?www.higithub.com'
```
