### ISSUE TITLE
Certain URLs are stuck as http://localhost

### ISSUE THREAD

**Issue by n3rd3x3** [searxng/searxng#1062]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
2022.04.06-4135a740
**How did you install SearXNG?**
 Using searxng-docker
**What happened?**
Certain parts of the website use localhost instead of the specified domain name, such as redirecting the user to `localhost` after saving settings, and setting localhost as the search URL (see below image.)
![Screenshot from 2022-04-06 13-39-45](https://user-images.githubusercontent.com/57784409/162045548-c9d46103-2008-4f6b-a125-8aade0f36037.png)

**How To Reproduce**
1. Install SearXNG using docker-compose
2. Forward port 8080 to port 80 (I used nginx for this)
3. Observe issues listed above

**Expected behavior**
The domain name would be dynamically changed to reflect the domain name you are currently on.

**Screenshots & Logs**
![Screenshot from 2022-04-06 13-39-45](https://user-images.githubusercontent.com/57784409/162045548-c9d46103-2008-4f6b-a125-8aade0f36037.png)

**Additional context**

**Comment by tiekoetter** [comment]
Make sure you have set the `BASE_URL` variable.

**Comment by n3rd3x3** [comment]
> Make sure you have set the `BASE_URL` variable.

I have done that in the .env file, and have even changed the variable in the `docker-compose` file, to no effect.

**Comment by tiekoetter** [comment]
So did you change anything from the default install? When I run searxng-docker and define the variables everything works as expected.

Would you mind sharing your config?

**Comment by n3rd3x3** [comment]
> So did you change anything from the default install? When I run searxng-docker and define the variables everything works as expected.
> 
> Would you mind sharing your config?

docker-compose.yaml
```
version: '3.7'

services:

  caddy:
    container_name: caddy
    image: caddy:2-alpine
    restart: on-failure
    network_mode: host
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy-data:/data:rw
      - caddy-config:/config:rw
    environment:
      - SEARXNG_HOSTNAME=${SEARXNG_HOSTNAME:-localhost}
      - SEARXNG_TLS=${LETSENCRYPT_EMAIL:-internal}
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
      - DAC_OVERRIDE

  filtron:
    container_name: filtron
    image: dalf/filtron
    restart: always
    ports:
      - "127.0.0.1:4040:4040"
      - "127.0.0.1:4041:4041"
    networks:
      - searxng
    command: -listen 0.0.0.0:4040 -api 0.0.0.0:4041 -target searxng:8080
    volumes:
      - ./rules.json:/etc/filtron/rules.json:rw
    read_only: true
    cap_drop:
      - ALL

  searxng:
    container_name: searxng
    image: searxng/searxng:latest
    restart: always
    networks:
      - searxng
    ports:
      - 8080:8080
    command: ${SEARXNG_COMMAND:-}
    volumes:
      - ./searxng:/etc/searxng:rw
    environment:
      - BIND_ADDRESS=0.0.0.0:8080
      - BASE_URL=https://${SEARXNG_HOSTNAME:-localhost}/
      - MORTY_URL=https://${SEARXNG_HOSTNAME:-localhost}/morty/
      - MORTY_KEY=${MORTY_KEY}
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
      - DAC_OVERRIDE

  morty:
    container_name: morty
    image: dalf/morty
    restart: always
    ports:
      - "127.0.0.1:3000:3000"
    networks:
      - searxng
    command: -timeout 6 -ipv6
    environment:
      - MORTY_KEY=${MORTY_KEY}
      - MORTY_ADDRESS=0.0.0.0:3000
    logging:
      driver: none
    read_only: true
    cap_drop:
      - ALL

networks:
  searxng:
    ipam:
      driver: default

volumes:
  caddy-data:
  caddy-config:
```

.env
```
# By default listen on https://localhost
# To change this:
# * uncomment SEARXNG_HOSTNAME, and replace <host> by the SearXNG hostname
# * uncomment LETSENCRYPT_EMAIL, and replace <email> by your email (require to create a Let's Encrypt certificate)

SEARXNG_HOSTNAME=https://search.n3rd3x3.xyz/
# LETSENCRYPT_EMAIL=<email>
# BASE_URL=https://search.n3rd3x3.xyz/
# automatically update settings to the new version
# comment this line if you made / will make some modifications to the settings
SEARXNG_COMMAND=-f

# use openssl rand -base64 33
MORTY_KEY=edited
```
