### ISSUE TITLE
A feature that prioritizes certain websites for higher placement in search results

### ISSUE THREAD

**Issue by nexryai** [searxng/searxng#1086]
**Is your feature request related to a problem? Please describe.**
I love this search engine. But sometimes it is less accurate than other search engines.

**Describe the solution you'd like**
It would be nice to have a feature (plugin) that prioritizes certain sites (such as stackoverflow) at the higher end of the search results.

**Comment by return42** [comment]
I fully understand what you mean .. on my instance i block domains / have a look at this discussion

- https://github.com/searxng/searxng/discussions/970

**Comment by dalf** [comment]
In kagi.com:
* in the preferences, you can block / lower / raise / pin domain names.
* in the result page, you can do the same: for each result, a popup appears when the mouse over a button (in SearXNG it can be the "cached" link). The popup contains information about the website [*] , and it is possible to set the ranking.

[*] the informations: ranking, when the domain was registered, is it a ads website ? is it fast ?, etc.... Google has done that for a time with less data.

kagi requires a login so the preferences can be stored on the server.

**Comment by return42** [comment]
> kagi requires a login so the preferences can be stored on the server.

Not very privacy friendly .. we should look for server-side solution that do not need to identify the user .. even if this means we can only offer fewer features to our end users.

**Comment by dalf** [comment]
> Not very privacy friendly .. 

Sure it doesn't fit into SearXNG, however I found the idea interesting.
In SearXNG, we have the missnamed "hostname_replace" plugin.
This plugin can already removes some results, this issue asks to prioritizes some website. The last part is to lower the priority of the some website.

For example:
* if hostname_replace is embedded into the ResultContainer.
* we add a new settings: `hostnames` (at the same level than `engines`):
```yaml
hostnames:
  replace:
    '(.*\.)?youtube\.com$': 'invidious.example.com'
    '(.*\.)?youtu\.be$': 'invidious.example.com'
    '(.*\.)?youtube-noocookie\.com$': 'yotter.example.com'
    '(.*\.)?reddit\.com$': 'teddit.example.com'
    '(.*\.)?redd\.it$': 'teddit.example.com'
    '(www\.)?twitter\.com$': 'nitter.example.com'
  remove:
    - example\.com$
  lower_priority:
    - another\.com$
  higher_priority:
    - website\.org$
```
