### ISSUE TITLE
Install scripts: remove filtron.sh and morty.sh

### ISSUE THREAD

**Issue by dalf** [searxng/searxng#1112]
* The [limiter plugin](https://github.com/searxng/searxng/blob/master/searx/plugins/limiter.py) can replace filtron. It is reliabled on a public instance.
* The embedded image proxy can replace morty.

```yaml
server:
  limiter: true  # can be disabled for a private instance
  image_proxy: true
redis:
  url: redis://....
```

---

searxng-docker is about to do the same: https://github.com/searxng/searxng-docker/pull/12
