### ISSUE TITLE
oscar nostalgia style for the simple theme

### ISSUE THREAD

**Issue by unixfox** [searxng/searxng#1169]
**Is your feature request related to a problem? Please describe.**
As a fan of oscar theme, I prefer oscar instead of the simple theme because everything is centered. And the colors of the dark theme are more pleasing to the eyes.

**Describe the solution you'd like**
It would be great to have an "oscar" style like for the simple theme, like a nostalgia theme so that people that are coming from the oscar can still feel at home.

Both available in dark and white theme.

In the style:
- Everything would be centered like on the oscar theme:
  <img src="https://user-images.githubusercontent.com/4016501/166516904-ba78d095-a555-4c2b-8a57-02c10aa8f01e.png" width="600">

- All the content would take as much space as possible, but without taking all the screen, like the oscar theme it would have a small border.
A good example is the GitHub wide: https://github.com/mdo/github-wide

- For the dark theme the colors would be the same as the oscar theme:
![image](https://user-images.githubusercontent.com/4016501/166517348-2ee26e04-c5fb-45e2-b1a8-667f4c818fb7.png)
No pure white texts like it's currently the case on the dark theme of the simple theme.

- (Nice to have) No icons for the links in the menu, including the preferences button.
![image](https://user-images.githubusercontent.com/4016501/166518028-86317d1d-820a-4efc-8a79-9f739291f2b1.png)

- Add back the instance name at the top left corner.
  Described in https://github.com/searxng/searxng/issues/3156

**Comment by mrpaulblack** [comment]
There should also be an option to center results for simple theme on desktop layout; maybe this can be part of the oscar nostalgia theme in the future...

**Comment by dalf** [comment]
An attempt to center the result page:

![image](https://user-images.githubusercontent.com/1594191/168423655-6660ee26-1883-44b0-b389-c5163671707b.png)

CSS (comment are existing CSS rules):

```css
main {
  display: flex;
  flex-direction: column;
  align-items: center;
}

#search {
  width: 100%;
  display: flex;
  flex-direction: column;
  align-items: center;
}

#results {
  /* margin-left: 10rem; */
  margin-left: 2rem;
}

.search_filters {
  /* margin-right: 0; */
  /* margin-left: 10.6rem; */
  margin-right: 2rem;
  margin-left: 2rem;
  width: 74rem;
}

#search_header {
  /* grid-template-columns: 3rem 1fr; */
  /* grid-template-areas: "logo search" "spacer categories"; */
  grid-template-columns: calc(50% - 37rem) 3rem 68rem;
  grid-template-areas: "na logo search" "na spacer categories";
}


.search_filters {
  /* margin-left: 2rem; */
  margin-left: 2.5rem;
}

#backToTop {
  left: calc(50% - 48rem + 56.3rem);
}
```

Issue: the light gray area does not expand to the edge of the window. It should be like in this screenshot:
![image](https://user-images.githubusercontent.com/1594191/168423810-08f3d1da-fc55-42f9-b990-01cfbc431feb.png)

... but here the rule to do that is "broken": `#search_header { width: calc(100vw - 4rem); }`

---

Alternative layout:
![image](https://user-images.githubusercontent.com/1594191/168423876-4e404b31-b182-4fe4-be70-677280ce441f.png)

Note: the logo is hidden because I don't know how to center the input and logo at the same time.

---

An option in the preferences could allow the user to center the result.
