### ISSUE TITLE
Bug: Searxng cant connect to any search engine (docker)

### ISSUE THREAD

**Issue by HiemSword** [searxng/searxng#1181]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2022.05.01-8a79eb4d

**How did you install SearXNG?**
Installed via the official wiki with docker, I then modified the docker-compose to disable caddy (I already have a reverse-proxy)
**What happened?**
Every time i try to search something, every engine times out, but i can ping the engines from inside the container

**How To Reproduce**
I really don't know

**Expected behavior**
The engines should not timeout

**Screenshots & Logs**
At startup I also see these errors
(too big for github, i copied everything in a pastebin here https://privatebin.net/?56f8c761b90264e3#6XaTNzKNYwuRmhY5Wr4UA8rnK39gcmuDqdTJVd8yEM76)

**Additional context**
Im running searxng on an Raspberry Pi 4 with 4gb of ram

This is my modified docker-compose
```
version: '3.7'

services:
  redis:
    container_name: redis
    image: "redis:alpine"
    command: redis-server --save "" --appendonly "no"
    tmpfs:
      - /var/lib/redis
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
      - DAC_OVERRIDE

  searxng:
    container_name: searxng
    image: searxng/searxng:latest
    volumes:
      - ./searxng:/etc/searxng:rw
    environment:
      - BASE_URL=https://localhost/
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

networks:
  default:
    external:
      name: net
```

**Technical report**
(in this case this error is thrown by google but its the same for every engine)
Error
  * Error: httpx.TimeoutException
  * Percentage: 100
  * Parameters: `(None, None, None)`
  * File name: `searx/search/processors/online.py:96`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

**Comment by dalf** [comment]
It seems the searxng container can't resolve DNS queries (the reported error is misleading).

In your log:
```
...
ValueError: 'soundcloud.com' does not appear to be an IPv4 or IPv6 address
...
httpcore.ConnectError: [Errno -2] Name does not resolve
...
socket.gaierror: [Errno -2] Name does not resolve
```

**Comment by return42** [comment]
> Installed via the official wiki with docker, 

Do we have a wiki?

**Comment by HiemSword** [comment]
I found the issue. The problem was that the container didn't use my host machine dns and couldn't make any request because i also have pihole hosted in the same raspberry, and it also appears that Alpine has some weird problems with dns and docker.
@dalf thanks for the help!

**Comment by PlexSheep** [comment]
@HiemSword I have the same problem. What did you do to fix the issue?

Edit a fix i found for me was to add a dns part in my docker-compose.yml.
here is my full config which produces a working instance for me:

```
version: '2.1'
services:
  flame:
    image: searxng/searxng
    container_name: searxng
    volumes:
      - /docker/searxng/searxng:/etc/searxng
    ports:
      - 8082:8080
    environment:
      - BASE_URL=https://searxng.homeserver.box
      - INSTANCE_NAME=searxng
    dns: 192.168.178.1
    restart: unless-stopped
```
