### ISSUE TITLE
Add goo engine

### ISSUE THREAD

**Issue by nexryai** [searxng/searxng#1374]
**Working URL to the engine**
https://search.goo.ne.jp/web.jsp?MT=searxng&FR=1

**Why do you want to add this engine?**
goo is a Japanese search engine. This search engine uses Google results.
This is useful for those who want to use Google results when SeaerXNG receives a reCAPTCHA from other search engines such as Google or Startpage.

**How can SearXNG fetch the information from this engine?**
I suggest using the Xpath engine.

**Applicable category of this engine**
I think it would be classified as "general".

**Additional context**
This search engine probably supports only Japanese.

**Comment by unixfox** [comment]
Not sure if it's relevant when we already have the google engine and you can bypass the captcha using `use_mobile_ui: true`.

And search.goo.ne.jp is very slow to load, at least from europe.

**Comment by nexryai** [comment]
I'm closing this issue as there doesn't seem to be much demand for it. For anyone who needs it: add the following to the engine settings in `settings.yml` if you want to add it
```
  - name: goo
    shortcut: goo
    engine: xpath
    paging: true
    search_url: https://search.goo.ne.jp/web.jsp?MT={query}&FR={pageno}0
    url_xpath: //div[@class="result"]/p[@class='title fsL1']/a/@href
    title_xpath: //div[@class="result"]/p[@class='title fsL1']/a
    content_xpath: //p[contains(@class,'url fsM')]/following-sibling::p
    first_page_num: 0
    categories: [general, web]
    timeout: 4.0
    disabled: false
    about:
      website: https://search.goo.ne.jp
      use_official_api: false
      require_api_key: false
      results: HTML
```
