### ISSUE TITLE
Just installed and see a blank page.

### ISSUE THREAD

**Issue by Littlemanjr2** [searxng/searxng#1399]
When I go to the URL all I see is a blank white page. The sever is up, service running, I'm not using a domain name just the local IP.

**Comment by mrpaulblack** [comment]
Hi @Littlemanjr2 ,
Can you please open up the dev tools in your browser with F12, go to the network tab and do a search... Please let me know if the HTTP status code for the search is HTTP 429 or 200...

**Comment by include** [comment]
Same behavior here. I am running the latest `searxng/searxng-docker`.

```
$ http rasp2
HTTP/1.1 200 OK
Content-Length: 0
Date: Sat, 02 Jul 2022 16:02:50 GMT
Server: Caddy
```

My settings are:

```
use_default_settings: true
general:
  instance_name: pipoka
search:
  safe_search: 0
  autocomplete: ""
  default_lang: ""
  formats:
    - html
server:
  secret_key: "FOOBAR"
  limiter: false
  image_proxy: false
ui:
  default_theme: simple
redis:
  url: redis://redis:6379/0
```

_edit: added settings block_
