### ISSUE TITLE
Manage HTTP headers

### ISSUE THREAD

**Issue by dalf** [searxng/searxng#140]
Currently, the default HTTP headers are set in [settings.yml](https://github.com/searxng/searxng/blob/73dbee45a649bdb6363717be0670bf4f35bf06a9/searx/settings.yml#L47-L52)

Another version in [searx-docker](https://github.com/searx/searx-docker/blob/abd5079b87e8c50e87c23e7b72cfcfcaa087fa47/Caddyfile#L34-L59) includes more headers. 

* See https://owasp.org/www-project-secure-headers/ 
   * "Best Practices" tab
   * [X-XSS-Protection](https://owasp.org/www-project-secure-headers/#x-xss-protection): _it is recommended to set the header as X-XSS-Protection: 0_

So currently:
* Content-Security-Policy is set in searx-docker but otherwise except if the administrator look at different locations.
* Administrators who do not update their settings.yml, won't have a secure setup.
* Some other administrator will set theirs HTTP headers in the reverse proxy once for all.

Looking at owasp.org, the HTTP headers need regular maintenance.

----

This issue suggests to define the default headers directly a place that is keep up to date: the code, so the configuration is not spread into different locations.

An option can let the administrator override them if requires.

About Content-Security-Policy: 
* a default can be set at first, see [Whoogle](https://github.com/benbusby/whoogle-search/blob/904091f44032961c6d494eb667862c49b5a695f7/app/routes.py#L100-L102)
* in a second time, the engines can returns a list of external website to include in the CSP header.

**Comment by return42** [comment]
Just want to leave some notes and links here ...

- [Make HTML templates more CSP compliant](https://github.com/searxng/searxng/issues/57)
- engines might have their own CSP requirements, e.g. `img-src 'self' data:` from  google.-images (and other): [`Header set Content-Security-Policy "img-src 'self' data: ;"`](https://github.com/searx/searx/blob/5f7056cf37a776e7aae151a4d1f5560f1bd0472f/searx/engines/google_images.py#L7-L12)

**Comment by dalf** [comment]
> engines might have their own CSP requirements

* simple solution: set the right value in settings.yml
* more elaborate: the result of an engine can add value to the CSP header (in addition to normal result, infoboxes, engine-data).

**Comment by return42** [comment]
> more elaborate: the result of an engine can add value to the CSP header (in addition to normal result, infoboxes, engine-data).

Hm I think it is better to know all http headers at startup time of the application, I mean after all engines are initialised,the CSP sides should be known.  Like you suggested ..

> in a second time, the engines can returns a list of external website to include in the CSP header.

This should be done when [engines are loaded](https://searxng.github.io/searxng/src/searx.engines.html#searx.engines.load_engines).

May be we add a new variable to the namespace of engine's python module which can be configured in the [server:](https://searxng.github.io/searxng/admin/engines/settings.html#server) section and in the [Engine Settings](https://searxng.github.io/searxng/admin/engines/settings.html#engine-settings) ...

```yaml

server:
  ...
  # list of CSP directives see https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy
  csp_directives:
    - "default-src 'self';" # https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/default-src
    - ...

...

engines:
  - name: example engine
    engine: example
    ...
    csp_directives:
      - "img-src 'self' data: ;" # https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/img-src
      - ...
```

**update** csp_directives can be a list like:

```yaml

server:
  ...
  # dict of CSP directives see https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy
  csp_directives:
    default-src: "'self'" # https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/default-src
    ...: ...

...

engines:
  - name: example engine
    engine: example
    ...
    csp_directives:
      img-src: 'self' data:" # https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/img-src
      ...: ...
```
**update** 

Directives from the engines are additive:

    Content-Security-Policy: img-src <engine-1.csp_directive.img-src> <engine-1.csp_directive.img-src>;

should CSP directives in the `server:` section win over same directives from a engine?

**Comment by dalf** [comment]
About `img-src` :
* when the image proxy is enabled, it nearly works with only `self data:`.
* nearly, because javascript requests can loads some images so `self data:` won't be enough.
  Example OSM tiles: in this case `img-src: "https://*.tile.openstreetmap.org"` must remains.

Perhaps something like this:
```yaml
- engine: google_image
  csp_directives:
    img-src: data:

- engine: openstreetmap
   csp_directives:
     img-src:
        - value: "https://*.tile.openstreetmap.org"
        - proxified: false
```

Also, a plugin that rewrite the URL must also rewrite the CSP.
If the `/image_proxy` is a plugin, it can rewrite the "img_src" field.
