### ISSUE TITLE
Brave: Too many request

### ISSUE THREAD

**Issue by GuillaumeHemmen** [searxng/searxng#1651]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**

2022.07.31-1fbb514a

**How did you install SearXNG?**

Using SearXNG via docker-compose (official image searxng/searxng:latest)

**What happened?**
When searching, I get the following message from the brave search engine: 

> Error! Engines cannot retrieve results:
> brave ( [too many requests](https://searxng.van-hemmen.com/stats?engine=brave) )

**How To Reproduce**
- head to https://searxng.van-hemmen.com
- do a search
- see the error message

**Expected behavior**
The engine should work. 

**Screenshots & Logs**
The above content should be enough.

**Additional context**
The default settings are in place for this engine. In fact, nearly is vanilla and only a few things are overridden, see configuration bellow:
```
# see https://docs.searxng.org/admin/engines/settings.html#use-default-settings
use_default_settings: true
server:
  # base_url is defined in the SEARXNG_BASE_URL environment variable, see .env and docker-compose.yml
  secret_key: "REDACTED"
  limiter: true  # can be disabled for a private instance
  image_proxy: true
ui:
  static_use_hash: true
redis:
  url: redis://redis:6379/0
engines:
  - name: google
    engine: google
    shortcut: go
    # see https://searxng.github.io/searxng/src/searx.engines.google.html#module-searx.engines.google
    use_mobile_ui: true
    # additional_tests:
    #   android: *test_android
```
====================================
I was not able to find anything helpful to solve this problem aside from #388 who was closed for not providing enough information. I hope that my ticket is properly filled, if not please tell me what's missing and how I can help :-)
