### ISSUE TITLE
Add the Ecosia search engine

### ISSUE THREAD

**Issue by MuadDibIII** [searxng/searxng#1675]
**Working URL to the engine**
[]https://www.ecosia.org/search?method=index&q=%s

**Why do you want to add this engine?**
 This is a privacy and ecology search engine, witch plant trees in exchange of users searches

**Features of this engine**
This is a privacy and ecology search engine, witch plant trees in exchange of users searches

**How can SearXNG fetch the information from this engine?**
general, images, map, news, videos

**Additional context**

**Comment by tiekoetter** [comment]
```
  - name: ecosia
    engine: xpath
    shortcut: eco
    time_range_support: true
    time_range_url: '&freshness={time_range_val}'
    time_range_map:
      day: 'day'
      week: 'week'
      month: 'month'
      year: 'year'
    results_xpath: //div[@class = "result__info" and not(descendant::div[contains(@class, "tooltip")])]
    search_url: https://www.ecosia.org/search?q={query}{time_range}&p={pageno}
    url_xpath: ./a
    title_xpath: ../div[@class = "result__title"]
    content_xpath: ../../div[@class = "result__columns"]
    suggestion_xpath: //div[@class = "related-queries__links"]/a
    paging: true
    first_page_num: 0
    disabled: true
    categories: [general, web]
    timeout: 3.0
    about:
      website: https://www.ecosia.org
      wikidata_id: Q1282139
      use_official_api: false
      require_api_key: false
      results: HTML
```

This is more or less the XPath implementation for the Ecosia web search.

Note: Ecosia seems to respond with code `503` when it is being accessed via some networks. This needs to be investigated.
