### ISSUE TITLE
Bug: elasticsearch engine

### ISSUE THREAD

**Issue by ErezAmihud** [searxng/searxng#2034]
Using searxng-docker
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2022.12.16-b9274821

I set the engine in the settings to the following:
```
- name: elasticsearch
    shortcut: es
    engine: elasticsearch
    base_url: http://localhost:9200
    username: elastic
    password: changeme
    index: crawl-data
    # available options: match, simple_query_string, term, terms, custom
    query_type: match
    # if query_type is set to custom, provide your query here
    #custom_query_json: {"query":{"match_all": {}}}
    #show_metadata: false
    disabled: false
```

and with the docker-compose:
```
version: '2'
services:
  ache:
    image: vidanyu/ache
    command: startCrawl -c /config/ -s /config/docker.seeds -o /data -e crawl-data
    ports:
    - "8080:8080"
    volumes:
    - ./data-ache/:/data
    - ./:/config
    links:
    - elasticsearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.22
    environment:
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./data-es/:/usr/share/elasticsearch/data # elasticsearch data will be stored at ./data-es/
    ports:
      - 9200:9200
  searx:
    container_name: searx
    image: searxng/searxng:latest
    restart: always
    command: ${SEARX_COMMAND:-}
    ports:
      - 8090:8090
    volumes:
      - ./searxng:/etc/searxng:rw
    environment:
      - BIND_ADDRESS=0.0.0.0:8090
      - BASE_URL=http://${SEARX_HOSTNAME:-localhost}/
    links:
    - elasticsearch
```
**What happened?**
After populating the elastic search I tried to search anything, and there was an error message about the engine, including the following traceback in the docker-compose logs:
```
2022-12-21 20:24:01,974 WARNING:searx.engines.elasticsearch: ErrorContext('searx/engines/elasticsearch.py', 54, 'raise ValueError(\'query format must be "key:value"\') from e', 'ValueError', None, ()) False
searx  | 2022-12-21 20:24:01,974 ERROR:searx.engines.elasticsearch: exception : query format must be "key:value"
searx  | Traceback (most recent call last):
searx  |   File "/usr/local/searxng/searx/engines/elasticsearch.py", line 52, in _match_query
searx  |     key, value = query.split(':')
searx  | ValueError: not enough values to unpack (expected 2, got 1)
searx  |
searx  | The above exception was the direct cause of the following exception:
searx  |
searx  | Traceback (most recent call last):
searx  |   File "/usr/local/searxng/searx/search/processors/online.py", line 160, in search
searx  |     search_results = self._search_basic(query, params)
searx  |   File "/usr/local/searxng/searx/search/processors/online.py", line 134, in _search_basic
searx  |     self.engine.request(query, params)
searx  |   File "/usr/local/searxng/searx/engines/elasticsearch.py", line 38, in request
searx  |     params['data'] = dumps(_available_query_types[query_type](query))
searx  |   File "/usr/local/searxng/searx/engines/elasticsearch.py", line 54, in _match_query
searx  |     raise ValueError('query format must be "key:value"') from e
searx  | ValueError: query format must be "key:value"
```
