### ISSUE TITLE
Can't switch language while Autodetect search language is activated

### ISSUE THREAD

**Issue by Tiritibambix** [searxng/searxng#2123]
**Version of SearXNG**
Searxng-docker  2023.01.21+674dae94 searxng/searxng:latest

**How did you install SearXNG?**
```
version: '3.7'
services:
  redis:
    container_name: searxng-redis
    image: "redis:alpine"
    restart: unless-stopped
    command: redis-server --save "" --appendonly "no"
    networks:
      - searxng
    tmpfs:
      - /var/lib/redis
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
      - DAC_OVERRIDE

  searxng:
    container_name: searxng
    image: searxng/searxng:latest
    restart: unless-stopped
    networks:
      - searxng
    ports:
     - "8082:8080"
    volumes:
      - ./Searxng/:/etc/searxng:rw
    environment:
      - SEARXNG_BASE_URL=https://my.domain.tld/
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
networks:
  searxng:
    ipam:
      driver: default
```

**What happened?**
Sometimes, Autodetect search language is wrong.
I then select (by scrolling, while hiting a key wold be easier) desired language, which launches the search again, but it returns back to bad language.

**How To Reproduce**
- Search for "vaseline lip therapy"
- It autodetects Polski
- Switch to French
- It switches back to Polski

**Expected behavior**
It should relaunch the search with selected language
Language should be selectable by hitting a key (eg F for French) to avoid scrolling
