### ISSUE TITLE
Add kagi.com

### ISSUE THREAD

**Issue by toyboatcash** [searxng/searxng#2247]
**Working URL to the engine**
(https://kagi.com/search?q=)

**Why do you want to add this engine?**
kagi has their own index of the finest results, augmented by the results from the best search engines on the market. 

**Features of this engine**
kagi has their own index, Doesn't track its users, fast, clutter-free search experience

**How can SearXNG fetch the information from this engine?**
Session Link This URL can be used to automatically log you into Kagi, as long as you remain logged in to this session. Do NOT share this link with anyone else! https://kagi.com/search?token= or https://help.kagi.com/kagi/search-api/overview.html 

**Applicable category of this engine**
general, Images, Videos, News, Maps 

**Additional context**
https://github.com/kagisearch/kagi-docs/discussions/24

-----

Related:

- https://github.com/searxng/searxng/pull/6182
- https://github.com/searxng/searxng/pull/4220

**Comment by gatunet** [comment]
I was looking into making a PR for adding Kagi, but to access the search api you need an [special account and you pay $25 for 1000 queries](https://help.kagi.com/kagi/api/search.html), so in theory it could be done easily, but I don't think people would use it(or maybe even be allowed to, given that you have to ask for the special team account).

Also I don't think we should implement this engine without following their guidelines, for example by keep using the token and parsing the results, because this in a way hurts them, and they at least [seam to care about privacy](https://kagi.com/privacy), so I think if we do this without using their API and paying the proper amount we'll be hurting a privacy respecting search engine.

They do [seam open to feedback and requests](https://github.com/kagisearch/kagi-docs/discussions/categories/kagi-search-api-feature-requests-ideas), so maybe try to talk about just lifting the special account thing, but then there's the price which is a problem for heavy users and I don't think they would be open to change that.

**Comment by lolcatw** [comment]
I looked at their API myself, they piss me off. They load all of the page's data through websockets (json).

**Comment by unixfox** [comment]
@lolcatw if you add `html/` before `/search` then you get the javascriptless version which is probably easier to parse since it's just HTML.

https://kagi.com/html/search?q=ok

**Comment by lolcatw** [comment]
@unixfox oh sweet, I'll look into it...

**Comment by gmemstr** [comment]
> They load all of the page's data through websockets (json).

Not quite sure where you got this from, as their own API docs[1] says you can just GET an endpoint and recieve a reasonable looking JSON response. Should be trivial to implement.

[1]: https://help.kagi.com/kagi/api/search.html

**Comment by lolcatw** [comment]
Oh that might've changed since then. I'm also aware they have a noJS version available now, which makes all of this irrelevant.

**Comment by richardklafter** [comment]
For anyone else who finds this issue kagi is easy to add:

1. make a [team account](https://help.kagi.com/kagi/plans/team-plan.html)
2. go here https://kagi.com/settings/api and get an API key.
3. add engine below to your config setting your api key

There are no longer any manual approvals required


```
  - name: kagi
    engine: json_engine
    shortcut: kag
    categories: general
    paging: true
    search_url: https://kagi.com/api/v0/search?q={query}
    headers:
      Authorization: "Bot <YOUR_API_KEY_HERE>"
    results_query: data
    url_query: url
    title_query: title
    content_query: snippet
    timeout: 5
    disabled: false
    about:
      website: https://www.kagi.com/
      official_api_documentation: https://help.kagi.com/kagi/api/search.html
      use_official_api: true
      require_api_key: true
      results: JSON
```

**Comment by scoobie517** [comment]
> For anyone else who finds this issue kagi is easy to add:
> 
>     1. make a [team account](https://help.kagi.com/kagi/plans/team-plan.html)
> 
>     2. go here https://kagi.com/settings/api and get an API key.
> 
>     3. add engine below to your config setting your api key
> 
> 
> There are no longer any manual approvals required
> 
> ```
>   - name: kagi
>     engine: json_engine
>     shortcut: kag
>     categories: general
>     paging: true
>     search_url: https://kagi.com/api/v0/search?q={query}
>     headers:
>       Authorization: "Bot <YOUR_API_KEY_HERE>"
>     results_query: data
>     url_query: url
>     title_query: title
>     content_query: snippet
>     timeout: 5
>     disabled: false
>     about:
>       website: https://www.kagi.com/
>       official_api_documentation: https://help.kagi.com/kagi/api/search.html
>       use_official_api: true
>       require_api_key: true
>       results: JSON
> ```

For me this brings an authentication error: 401Unauthorizedkagi.com
Edit: no it works fine. You need to ask for search api access at kagi support

**Comment by holysoles** [comment]
Can confirm the above works great. They approved my access very quickly.

They did note in their reply email that they plan to add more features and have "better pricing" soon. Given the current pricing is $0.025/query, compared to $0.016/query for using their UI with the "Basic" plan, I hope they make the change since that will probably be a blocker for me long term.

Would recommend setting a `tokens` value so that someone doesn't burn all your API credits.

**Comment by ZombieLurker** [comment]
Just wanted to add some good news, they denied me access to the beta for the Search API yesterday because they said they will be doing onboarding for regular access to the Search API within the next 2 weeks at $0.012 per search query. That is like half the cost of the beta currently. Just figured I'd put this here so people who run across this like I did are aware.

**Comment by becks0815** [comment]
The API implementation mentioned above fails - at least for me. And then we have a PR submitted to add kagi as search engine into the core, which was denied/closed. Any other ideas on how to add kagi?

**Comment by becks0815** [comment]
Partitial fix. It searches kagi, but the results are not shown in Firefox

```
 - name: kagi
    engine: json_engine
    shortcut: kag
    categories: general
    paging: true
    search_url: https://kagi.com/api/v1/search
    method: POST
    request_body: '{{"query": "{query}", "page": {pageno}}}'
    headers:
      Authorization: "Bearer <INSERT_API_KEY_HERE>"
    results_query: data.search
    url_query: url
    title_query: title
    content_query: snippet
    first_page_num: 1
    timeout: 5
    disabled: false
    about:
      website: https://www.kagi.com/

```
