### ISSUE TITLE
No google results anymore

### ISSUE THREAD

**Issue by systemofapwne** [searxng/searxng#2287]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
searxng-docker: 2023.3.24+64fea2f9

**How did you install SearXNG?**
Official docker

**What happened?**
Using google as engine gives no results. However using google for autocompletion still works

**How To Reproduce**
Set up google as your only engine. 
Search for anything.

**Expected behavior**
Results will be returned

**Screenshots & Logs**
Results are empty
![image](https://user-images.githubusercontent.com/30482165/228183793-baf4f488-58c8-430a-82fd-869e434421fd.png)

**Additional context**
I noticed this behavior by today. Maybe it already happened a few days before - I don't know. It was certainly working properly last week.

Hear is a a sanitized version of my settings.yml, that only enables google (for debugging purpose):
```yaml
use_default_settings: true

general:
  instance_name: "SearXNG"
  privacypolicy_url: "https://example.org"
  donation_url: false
  contact_url: false
  enable_metrics: true

brand:
  wiki_url: "https://example.org"

search:
  # Filter results. 0: None, 1: Moderate, 2: Strict
  safe_search: 0
  # Existing autocomplete backends: "dbpedia", "duckduckgo", "google", "yandex",
  # "seznam", "startpage", "swisscows", "qwant", "wikipedia" - leave blank to turn it off
  # by default.
  #autocomplete: "startpage"
  autocomplete: "google"
  # minimun characters to type before autocompleter starts
  autocomplete_min: 4
  # Default search language - leave blank to detect from browser information or
  # use codes from 'languages.py'
  default_lang: "all"
  # Available languages
  # languages:
  #   - all
  #   - en
  #   - en-US
  #   - de
  #   - it-IT
  #   - fr
  #   - fr-BE
  # ban time in seconds after engine errors
  ban_time_on_fail: 5
  # max ban time in seconds after engine errors
  max_ban_time_on_fail: 120
  # remove format to deny access, use lower case.
  # formats: [html, csv, json, rss]
  formats:
    - html

ui:
  # Custom static path - leave it blank if you didn't change
  static_path: ""
  static_use_hash: true
  # Custom templates path - leave it blank if you didn't change
  templates_path: ""
  # query_in_title: When true, the result page's titles contains the query
  # it decreases the privacy, since the browser can records the page titles.
  query_in_title: true
  # infinite_scroll: When true, automatically loads the next page when scrolling to bottom of the current page.
  infinite_scroll: true
  # ui theme
  default_theme: simple
  # center the results ?
  center_alignment: false
  # URL prefix of the internet archive, don't forgett trailing slash (if needed).
  # cache_url: "https://webcache.googleusercontent.com/search?q=cache:"
  # Default interface locale - leave blank to detect from browser information or
  # use codes from the 'locales' config section
  default_locale: ""
  # Open result links in a new tab by default
  # results_on_new_tab: false
  theme_args:
    # style of simple theme: auto, light, dark
    simple_style: dark

server:
  # base_url is defined in the SEARXNG_BASE_URL environment variable, see .env and docker-compose.yml
  secret_key: "<REDACTED>"  # change this!
  limiter: false  # can be disabled for a private instance
  image_proxy: true
  method: "GET"     # More History-Stable

redis:
  url: redis://web_redis_1:6379/0

engines:
  - name: google
    weight: 3
    use_mobile_ui: false
    disabled: false
  - name: duckduckgo
    disabled: true
  - name: qwant
    disabled: true
  # Startpage became too slow: Disabling it. Using "real google" now...
  - name: startpage
    disabled: true
    weight: 3

  - name: google play apps
    disabled: true

  - name: twitter
    disabled: true

  - name: apk mirror
    disabled: true

  - name: fdroid
    disabled: true

  - name: npm
    disabled: true
```
