### ISSUE TITLE
Can't override formats when using use_default_settings

### ISSUE THREAD

**Issue by alexiri** [searxng/searxng#2337]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**

2023.4.12+b07e44e5

**How did you install SearXNG?**

Official docker image

**What happened?**

I'm trying to configure the docker image for API access and if I set `use_default_settings: true` in `settings.yml`, I can't seem to override the default values of `formats`.

**How To Reproduce**

Create the following `settings.yml` and instantiate a docker container that uses it:

```yaml
use_default_settings: true
server:
  secret_key: "bla"
  limiter: false
  formats:
    - html
    - json
```

API access is disabled:

```
~> curl -kLX GET --data-urlencode q='langchain' -d format=json http://localhost:8080
<!doctype html>
<html lang=en>
<title>403 Forbidden</title>
<h1>Forbidden</h1>
<p>You don&#39;t have the permission to access the requested resource. It is either read-protected or not readable by the server.</p>
```

If I don't use `use_default_settings: true`, then my `settings.yml` has to be a bit longer, but the API works:

```yaml
#use_default_settings: true
server:
  secret_key: "bla"
  limiter: false
  formats:
    - html
    - json

engines:
  - name: google
    engine: google
    shortcut: go

doi_resolvers:
  oadoi.org: 'https://oadoi.org/'
  doi.org: 'https://doi.org/'
  doai.io: 'https://dissem.in/'
  sci-hub.se: 'https://sci-hub.se/'
  sci-hub.st: 'https://sci-hub.st/'
  sci-hub.ru: 'https://sci-hub.ru/'

default_doi_resolver: 'oadoi.org'
```

**Expected behavior**

It should be possible to override the value of formats while using `use_default_settings: true` for everything else.

**Screenshots & Logs**

**Additional context**

**Comment by alexiri** [comment]
Ok, never mind, I realized my mistake: `formats` belongs under `search`, not `server`. The correct yml looks like this:

```yaml
use_default_settings: true
server:
  secret_key: "bla"
  limiter: false

search:
  formats:
    - html
    - json
```
