### ISSUE TITLE
search_url parameter not returning results from specific sites

### ISSUE THREAD

**Issue by nordkorea** [searxng/searxng#2431]
```
- name: google_images
  shortcut: gi
  categories:
    - images
  search_url: https://www.google.com/search?q={query}+site:unsplash.com+OR+site:pexels.com+OR+site:pixabay.com&tbm=isch&safe=active
```
I have tried to use this as a workaround to make Google Images limit search results to specific sites. I have been trying to find a solution to this for the past three weeks. Hope what I am doing is right.
The `search_url` is supposed to return results from unsplash.com, pexels.com and pixabay.com - as far as I know. But instead, it returns results from all over the web.
