### ISSUE TITLE
Infinite scroll runs into an infinite loop / or hangs after loading the second page

### ISSUE THREAD

**Issue by return42** [searxng/searxng#2480]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**

current master branch

**How did you install SearXNG?**

create a `/etc/searxng/settings.yml`

```yaml
use_default_settings: true

ui:
  infinite_scroll: true

engines:

  - name: google videos
    categories: general

  - name: bing videos
    categories: general
```

and then start ``make run``

**How To Reproduce**

Search for term "foo" .. in the response the infinite scroll goes into wild and loads pages in an endless loop (without any scrolling of the user).

----

I have tried several things, mostly the error occurs when I search for the term "foo" and when a video engine is defined in the category "general".

The behavior is very strange, sometimes the infinite scroll hangs even after loading the contents of a second page and then switches back to normal mode where you can select the pages individually ... sometimes all pages are loaded endlessly ... it seems to be related to the categories and to the results in the hit list ... but I do not know exactly yet.
