### ISSUE TITLE
Add an option to search for content within specified lists of websites

### ISSUE THREAD

**Issue by LeoBoudet** [searxng/searxng#2507]
Hello!

I have noticed when I am looking for something on the search engines that the results can be polluted by numerous websites whose only quality is to have a good SEO but no relevant information to share.

In order to solve this problem, that many of us face apparently, I thought about a way of creating lists of resources that a user would have previously selected to be browsed.

Let's say I am working on a biology article and I already know several web resources that I trust and that I would like to browse easily. I could simply select my custom list called "biology" and type my requests directly to be browsed within the resources named on that list.

I have looked around for a while to find such a feature but didn't manage to find anything so I am proposing it here, because I think that projects like SearXNG are some of the most obvious to develop such features.

I've only find a blocking list request here:
https://github.com/searx/searx/issues/2001

If you are interested, you can find my complete reflection on that matter in this article, that extends this idea to other features:
https://synergeticdesign.substack.com/p/software-overlay-for-metasearch-engines

If you already know a tool to do so, please share it in the comments, I am sure it would help many people.

Thank you for your time,

Léo

**Comment by allendema** [comment]
Difficult cuz searxng has no index but:

_Option 1:_

Use an upstream engine which supports domain whitelisting/ranking like mojeek, brave. [0]
Under ```settings.yml```copy base upstream engine config, rename it and add you wanted domains.
This step can be repeated.




<details>
<summary> Working mojeek config with whitelisted domains for e.x python </summary>
(base mojeek + added foc param and cookies)

```yaml
  - name : mojeekpython
    shortcut: mjkpy
    engine: xpath
    paging : True
    search_url : https://www.mojeek.de/search?q={query}&s={pageno}&lang={lang}&lb={lang}&foc=python
    results_xpath: //ul[@class="results-standard"]/li/a[@class="ob"]
    url_xpath : ./@href
    title_xpath : ../h2/a
    content_xpath : ..//p[@class="s"]
    suggestion_xpath : //div[@class="top-info"]/p[@class="top-info spell"]/em/a
    first_page_num : 0
    page_size : 10
    disabled : True
    weight: 1.1
    display_error_messages: False
    cookies:
        foc_python: i=python-forum.de,python.org,realpython.com,stackoverflow.com&e=pinterest.com,www.w3schools.com,www.ionos.de
```
</details>

<details>
<summary>Used-to-work previously Brave config with whitelisted domains for e.x tech blogs </summary>

[https://github.com/searxng/searxng/compare/master...allendema:searxng:brave-goggles](https://github.com/searxng/searxng/compare/master...allendema:searxng:brave-goggles)
[https://github.com/searxng/searxng/commit/12d9de269825759eb3ce15f22357f39968e2c513](https://github.com/searxng/searxng/commit/12d9de269825759eb3ce15f22357f39968e2c513)

</details>

_Option 2:_

Requires changes to javascript/html code:

- type a list of wanted domains in a box under preferences
- save them in searxng
- make those lists availiable in a dropdown list smiliar to locale, safesearch, time.
- convert selected list to upstream format (cookie) [1]

> [0] [https://search.brave.com/help/goggles](https://search.brave.com/help/goggles)
> [1] [https://www.mojeek.com/focus/dashboard](https://www.mojeek.com/focus/dashboard)
