### ISSUE TITLE
Unable to set additional parameters for google engine

### ISSUE THREAD

**Issue by unixfox** [searxng/searxng#2513]
If you try to set a proxy for btdigg for example it will send the request to a proxy:
```
- name: btdigg
    engine: btdigg
    shortcut: bt
    proxies:
       all://:
        - socks5h://127.0.0.1:9050
```

But for google it doesn't work:

```
- name: google
    engine: google
    shortcut: go
    proxies:
      all://:
        - socks5h://127.0.0.1:9050
```

You can also try any other parameter like `enable_http2: false`, HTTP2 will still be used.

I'm not sure if it affects other engines too.

@return42 do you know what is going on?
