### ISSUE TITLE
[FEATURE REQUEST] external list file for hostname_replace

### ISSUE THREAD

**Issue by DeltaTangoLima** [searxng/searxng#2619]
## Is your feature request related to a problem? Please describe.
No

## Describe the solution you'd like
The `hostname_replace` feature is absolutely killer, and the main reason I started using searxng. It means I can totally eliminate all the crap websites out there.

What would be really useful would be if lists of hostnames could be stored in external lists, for replace and block, respectively. Ideally these would be in a simplified format so an admin can quickly (or programmatically) update text files, rather than having to modify the settings yaml file directly.

I guess an `include` capability is really what I'm asking for, in `settings.yaml`, and then breaking the `hostname_replace` section into sub-sections for replace vs block:

```
# Configuration of the "Hostname replace" plugin:
#
hostname_replace:
   replacelist:
      !include replacements.txt
   blocklist:
      !include blocklist.txt
```

### replacelist
This file could store the regex/replace pairs, one per line, just as in the existing yaml today.

### blocklist
This file could just store the regex for the host/site/domain, and searxng can just assume a `: false` at the end of each line, when it reads the file in.

## Describe alternatives you've considered
Writing my own script to modify the yaml. I still might. ;)

## Additional context
None
