### ISSUE TITLE
Internal Server Error when searching for specific search string

### ISSUE THREAD

**Issue by cscherrNT** [searxng/searxng#2661]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**

`2023.2.15+52f6bc74`

**How did you install SearXNG?**

I am using the docker version, the docker-compose file is appended below.

**What happened?**

When searching for `Missing \endcsname inserted.` specifically, the search produces an internal server error (HTML 500). Other searches are possible. This occurs in both the graphical search bar and when searching with firefox directly.

This search string came up when working on a LaTeX document, does searxng use some form of LaTeX processing for it's search strings?

My server is not overloades, and the problem seems to occur every time I search for this. Since it is a 500 error, I saw no need to test many clients. The error occurs with both `POST` and `GET`.

**How To Reproduce**

Search for `Missing \endcsname inserted.` specifically.

Use [this](https://search.cscherr.de/search?q=Missing+%5Cendcsname+inserted.) link to search on my selfhosted instance (with GET).

**Expected behavior**
Search for the given search string.

**Screenshots & Logs**

![grafik](https://github.com/searxng/searxng/assets/123484154/16e681ae-eb8c-4ddd-bdca-80128e516860)

![grafik](https://github.com/searxng/searxng/assets/123484154/c822bcd4-01db-438e-a91a-d6cb7e9647fc)

**Additional context**
When I search for something else, it works. Refreshing (and resending the data) also produces Internal Server Error (500). For example, searching for `foo`and `Missing \foo inserted.` works.

I run searxng with this docker-compose file:
```yml
version: '2.1'
services:
  searxng:
    image: searxng/searxng
    container_name: searxng
    volumes:
      - /srv/searxng/searxng:/etc/searxng
    ports:
      - 172.19.0.1:8004:8080
    environment:
      - BASE_URL=https://search.cscherr.de
      - INSTANCE_NAME=cscherr.de - Meta Search
    restart: unless-stopped
networks:
  default:
    external: true
    name: internal-subnet
```
