### ISSUE TITLE
Images load out of order and only half of them load when routing traffic through a tunnel (?)

### ISSUE THREAD

**Issue by y0nei** [searxng/searxng#2700]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
`2023.8.30+7af66736c`

**How did you install SearXNG?**
using searxng-docker

**What happened?**
So, for security i route all my services via a wireguard tunnel, i observed that while i do that, images in the image search behave wierdly and load out of order while some just wont load completely. I do have image proxy enabled in the searxng config.
My guess was a slow internet connection from the tunnel server, but after changing it from 1984.hosting to Hetzner, it keeps behaving the same. Now my domain (https://searx.headpat.exchange) runs from the Hetzner VPS without any tunneling going on, and all the images behave as expected, loading in order.  
My home network has a Download speed of **~400 Mbit/s** and an Upload of **~500 Mbit/s**, the searx.space results show a `6.577` Search response time as of 30/08/2023. When i was exposing services directly from my home IP, it worked properly without issues and additional delays.
I'm not sure why that is happening, could the latency between me and Hetzner in germany (i live in a neighboring country) be so much that it just times out?

**How To Reproduce**
Use https://github.com/DigitallyRefined/docker-wireguard-tunnel and follow the instructions on setting up a simple wireguard tunnel, push ports of SearXNG through the tunnel and expose it on the server.

**Expected behavior**
Images loading properly, in order like in most instances

**Screenshots & Logs**
Logs look completely normal, nothing unusual

**Additional context**
`settings.yml`
```yml
use_default_settings: true
server:
  secret_key: "itsjoever"
  limiter: true
  image_proxy: true
search:
  autocomplete: "startpage"
  autocomplete_min: 3
  default_lang: "all"
ui:
  static_use_hash: true
  center_alignment: true
  theme_args:
    simple_style: dark
redis:
  url: redis://redis:6379/0
outgoing:
  request_timeout: 6.0
```
