### ISSUE TITLE
Unable to select Vim-like hotkeys via settings.yml

### ISSUE THREAD

**Issue by kmac** [searxng/searxng#2898]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**

I'm using docker: searxng/searxng:latest

**How did you install SearXNG?**

Docker compose, using searxng/searxng:latest

**What happened?**

Since the removal of the VIM-like hotkeys plugin, there doesn't seem to be a way to select the VIM hotkeys via settings.yml. I'd like to be able to set it in the default config for my instance.

**How To Reproduce**

I have tried the following in settings.yml, both under the `ui` section and at the top-level:

```
ui:
  static_use_hash: true
  # query_in_title: When true, the result page's titles contains the query
  # it decreases the privacy, since the browser can records the page titles.
  query_in_title: true
  # infinite_scroll: When true, automatically loads the next page when scrolling to bottom of the current page.
  infinite_scroll: true
  # Open result links in a new tab by default
  results_on_new_tab: true
  hotkeys: vim

hotkeys: vim
```

**Expected behavior**

The default hotkey setting should be VIM, but it is set to the default SearxNG setting. I can't seem to set the default to 'vim'.

**Screenshots & Logs**

**Additional context**
