### ISSUE TITLE
[example] /etc/searx/settings.yml

### ISSUE THREAD

**Issue by return42** [searxng/searxng#29]
To share admin experience I want to leave my **actual** `/etc/searx/settings.yml` setup here. 

My searx setup has a weight on 

- safe-search
- german-speaking user base 
  - pure EN engines in categories 'general' and 'news' are disabled by default
  - german-speaking content like the one from mediathekviewweb are placed in category 'general'

**last update: 2021/06/13**

```yaml
use_default_settings: true

general:
  debug: false  # Debug mode, only for development
  instance_name: "SearXNG@darmarIT"  # displayed name

search:
  # Filter results. 0: None, 1: Moderate, 2: Strict
  safe_search: 2
  # Existing autocomplete backends: "dbpedia", "duckduckgo", "google",
  # "startpage", "swisscows", "qwant", "wikipedia" - leave blank to turn it off
  # by default.
  autocomplete: "duckduckgo"
  # Default search language - leave blank to detect from browser information or
  # use codes from 'languages.py'
  default_lang: ""

server:
  port: 8888
  # address to listen on
  bind_address: "127.0.0.1"
  secret_key: "ultrasecretkey"  # change this!
  # Set custom base_url. Possible values:
  #   false or "https://your.custom.host/location/"
  base_url: https://darmarit.org/searx
  # Proxying image results through searx
  image_proxy: false

engines:

  - name: duckduckgo
    disabled: false

  - name: fdroid
    disabled: false

  - name: apk mirror
    disabled: false

  - name: springer nature
    engine: springer
    shortcut: springer
    categories: science
    # get your API key from: https://dev.springernature.com/signup
    api_key: ""
    disabled: false
    timeout: 6.0

  - name: mediathekviewweb
    engine: mediathekviewweb
    shortcut: mvw
    categories: general

  # bing is broken
  #
  - name: bing
    disabled: true

  # core.ac response very slow (inital most often 10sec.)
  #
  - name: core.ac.uk
    engine: core
    categories: science
    shortcut: cor
    api_key: ''
    timeout: 6

  # duden has very often HTTP errors
  #
  - name: duden
    disabled: true

  # yahoo news are only english
  #
  - name: yahoo news
    disabled: true

  # yahoo language support does not work
  #
  - name: yahoo
    disabled: true

  # reddit does not support laguages
  #
  - name: reddit
    timeout: 3

```
