### ISSUE TITLE
Engine request: Marginalia

### ISSUE THREAD

**Issue by gabrielvicenteYT** [searxng/searxng#3034]
**Working URL to the engine**

https://search.marginalia.nu

**Why do you want to add this engine?**

This search engine has a lot of relatively unknown websites, and might help some people to use SearXNG as how Google was at the beginning (being able to actually search for things properly)

**Features of this engine**

Keyword-based results
Special Keywords
The engine searches exactly for the keywords you want.
Not tailored for big websites, can find every niche website

**How can SearXNG fetch the information from this engine?**

**Applicable category of this engine**

General, News, Science

**Additional context**

The engine might be hard to use, because of its own advantage: Not having large websites on top.
But if you use it to its maximum potential, you can even find very mysterious / obscure things (by that, I mean that they are not usually found anywhere).

**Comment by return42** [comment]
We already had marginalia in the past .. but we removed it in https://github.com/searxng/searxng/pull/2489 .. read the links in the #2489 and the issue https://github.com/searxng/searxng/issues/1673

**Comment by girlmaya** [comment]
> We already had marginalia in the past .. but we removed it in #2489 .. read the links in the #2498 and the issue #1673

Reading the linked issues, I don't understand why the engine was removed instead of tweaking it to not spam marginalia with unnecessary requests. Is it simply that no one was willing to rewrite the engine?

**Comment by return42** [comment]
> Is it simply that no one was willing to rewrite the engine?

Yes, feel welcome to implement ..

> instead of tweaking it to not spam marginalia with unnecessary requests. 

The big questions are: how to avoid *unnecessary requests* and what is a *unnecessary request*?

**Comment by troed** [comment]
This sounds like a misunderstanding. Viktor was pointing out that the default "public" API key to his marginalia instance is very limited. As can be seen here, those wanting to use marginalia as a search engine in their own searxng instances should just ask for their own API keys instead:

https://about.marginalia-search.com/article/api/

So, imho, the engine can be brought back - but unless an API key as been added it should not be possible to enable.

**Comment by girlmaya** [comment]
I agree, but it seems there was also an issue with the engine that would need to be fixed first to avoid spamming the API anyway

**Comment by omentic** [comment]
FYI, I am very happily running Marginalia as a JSON engine.

```yaml
engines:
  - name: marginalia
    engine: json_engine
    shortcut: mar
    categories: general
    paging: false
    # Key and license: https://www.marginalia.nu/marginalia-search/api/
    # index: 0 popular, 1 blogs, 2 big_sites, 3 default, 4 experimental
    search_url: https://api.marginalia.nu/<API-KEY>/search/{query}?index=4&count=20
    results_query: results
    url_query: url
    title_query: title
    content_query: description
    weight: 5
    timeout: 3.0
    about:
      website: https://www.marginalia.nu/
      official_api_documentation: https://api.marginalia.nu/
      use_official_api: true
      require_api_key: true
      results: JSON
```

I emailed Viktor about a personal key and he was happy to provide one. I also asked him about the multiple identical requests issue and he had the following to say in response:

> I honestly don't know what happened with that.  It may just have been a
bot that hit multiple frontends, since it shipped with the default
demo key.  I think they removed that and since then it's quieted down.

> Though I also added a workaround in my code, basically a response
cache, so that if the same query happens several times in quick
succession, the search engine doesn't bother using resources to
re-perform the actual query, it just gives a stored answer.
