### ISSUE TITLE
Docker environment variables do not overwrite settings.yml

### ISSUE THREAD

**Issue by Mnikley** [searxng/searxng#3083]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
27e26b3d658bb3bad0d5a204891b9b8e73ce8fc2 or searxng/2023.12.29+27e26b3d6

**How did you install SearXNG?**
docker image: searxng/searxng

**What happened?**
Environment variables defined in docker-compose.yml are not applied

**How To Reproduce**

try to change port address, e.g.:
```
  searxng:
    image: searxng/searxng
    container_name: searxng
    environment:
      - INSTANCE_NAME=testinstance
      - SEARXNG_URL=false
      - SEARXNG_BIND_ADDRESS=0.0.0.0
      - SEARXNG_PORT=1232
    restart: unless-stopped
    ports:
      - 1232:8080
```
**Expected behavior**
searxng instance running on port **1232**. The settings in the container are still set to port 8888:
```
docker exec -it searxng /bin/cat /usr/local/searxng/searx/settings.yml | grep server: -A 5
server:
  # If you change port, bind_address or base_url don't forget to rebuild
  # instance's environment (make buildenv). Is overwritten by ${SEARXNG_PORT}
  # and ${SEARXNG_BIND_ADDRESS}
  port: 8888
  bind_address: "127.0.0.1"
```
while the actual port seems to be **8080**:
```
curl searxng:8080
<!DOCTYPE html>
<html class="no-js theme-auto center-aligment-no" lang="en-EN" >
<head>
  <meta charset="UTF-8" />
  <meta name="description" content="SearXNG — a privacy-respecting, open metasearch engine">
  <meta name="keywords" content="SearXNG, search, search engine, metasearch, meta search">
  <meta name="generator" content="searxng/2023.12.29+27e26b3d6">
...
```
