### ISSUE TITLE
[question] simplify the proxy configuration ?

### ISSUE THREAD

**Issue by dalf** [searxng/searxng#342]
Currently it is possible to define this configuration
```yaml
proxies:
  all://:
    - socks5h://127.0.0.1:9050
    - socks5h://127.0.0.1:9051
  https://:
    - socks5h://127.0.0.1:9052
    - socks5h://127.0.0.1:9053
  https://*.wikipedia.org:
    - socks5h://192.168.0.12:1337
    - socks5h://192.168.0.13:1337
```

Is it really useful if we take into account the fact that it is possible to define a proxy configuration per engine?

In the above configuration the wikipedia requests are sent to other proxies, it can be done this way:

```yaml
outgoing:
  proxies:
    https://:
      - socks5h://127.0.0.1:9052
      - socks5h://127.0.0.1:9053
....
engines:
  - name: wikipedia
    engine: wikipedia
    shortcut: wp
    base_url: 'https://{language}.wikipedia.org/'
    network:
       proxies:
         all://:
           - socks5h://192.168.0.12:1337
           - socks5h://192.168.0.13:1337
```

So all requests sent by the wikipedia engine use the proxies on `192.168.0.*` whatever the target URL is.

I suggest to remove the mount point and keep only a list of proxy:
```yaml
outgoing:
  proxies:
    - socks5h://127.0.0.1:9052
    - socks5h://127.0.0.1:9053
....
engines:
  - name: wikipedia
    engine: wikipedia
    shortcut: wp
    base_url: 'https://{language}.wikipedia.org/'
    network:
       proxies:
         - socks5h://192.168.0.12:1337
         - socks5h://192.168.0.13:1337
```

ping @unixfox @MarcAbonce

**Comment by unixfox** [comment]
one engine can utilize a lot of different domains, like the google engine which seems to use all the google tld. without the ability to specify the proxy per engine it might be difficult to make the google engine working through a proxy.

**Comment by dalf** [comment]
Sorry, it was not clear or I didn't understand your answer.

The question is not: _should we remove the network configuration per engine ?_
But rather: for one network (= for one engine), should we remove the ability to dispatch the HTTP requests to different proxies according the URL ?

For example, is this kind of configuration useful? (= a list of proxies per domain names)
```yaml
engines:
  - name: google
    engine: google
    network:
       proxies:
         - all://:
           - socks5h://192.168.0.12:1337
           - socks5h://192.168.0.13:1337
         - https://www.google.be:
           - socks5h://10.0.0.100:8000
           - socks5h://10.0.0.101:8000
           - socks5h://10.0.0.102:8000
         - https://www.google.it:
           - socks5h://10.0.1.200:9000
           - socks5h://10.0.1.201:9000
           - socks5h://10.0.1.202:9000
```

Or is this one enough:
```yaml
engines:
  - name: google
    engine: google
    network:
       proxies:
           - socks5h://192.168.0.12:1337
           - socks5h://192.168.0.13:1337
           - ...
           - ...
```
