### ISSUE TITLE
media.ccc.de no video frame in standard videos

### ISSUE THREAD

**Issue by cy8aer** [searxng/searxng#3431]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**

2024.4.27+1e1fb59be 

**How did you install SearXNG?**

SearxNG ist installed via official docker container

**What happened?**

The new video frame does not work properly with the new frame functionality

**How To Reproduce**

* Search `!c3tv 37c3`
* Move to an official entry, like "37C3: Feierliche Eröffnung"
* Click the "Open Video" Button

**Expected behavior**

The video frame is opened with the playable video in it

**Screenshots & Logs**

The video frame is opened empty and a `.srt` file is downloaded (here 37c3-12338-deu-eng-fra-37C3_Feierliche_Eroeffnung.de.srt)

**Additional context**

Unfortunately I did not find any video which opens in the frame

Standard configuration

```yaml
  - name: media.ccc.de
    engine: ccc_media
    shortcut: c3tv
    # We don't set language: de here because media.ccc.de is not just
    # for a German audience. It contains many English videos and many
    # German videos have English subtitles.
    disabled: true
```
