### ISSUE TITLE
not returning json results, only html

### ISSUE THREAD

**Issue by im-fabian** [searxng/searxng#3541]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
2024.5.31+18fb701be (via docker)

**How did you install SearXNG?**
Via docker-compose:

```
  searxng:
    image: docker.io/searxng/searxng:latest
    container_name: searxng
    ports:
      - "127.0.0.1:8080:8080"
    networks:
     - internal_network
     - public_network
    environment:
     - SEARXNG_BASE_URL=http://searxng:8080
     - INSTANCE_NAME=HuggingSearch
    volumes:
     - /opt/hugging-chat/data/searxng:/etc/searxng
    cap_drop:
     - ALL
    cap_add:
     - CHOWN
     - SETGID
     - SETUID
```

**What happened?**
curl http://127.0.0.1:8080/search?q=test&engines=duckduckgo&format=json returns html results not json.

**How To Reproduce**
Setup searxng via docker compose. 
Enable json within settings.yml (search: formats: - json), restart docker container. Try to get json results via curl. 

**Expected behavior**
Should get results as json.

**Screenshots & Logs**

**Additional context**
