### ISSUE TITLE
all engines running into timeout

### ISSUE THREAD

**Issue by 0x5247** [searxng/searxng#3626]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2024.6.29+adaec6872

**How did you install SearXNG?**
docker

**What happened?**
When I searched for something I got this error
Error! Engines cannot retrieve results:

**Screenshots & Logs**
![Screenshot (61)](https://github.com/searxng/searxng/assets/143602102/d75c8003-964a-441f-8df4-45f98b1e8aea)

**Comment by return42** [comment]
This is not a google issue (I change the title) .. seems you have a problem with the internet connection since all engines have timeouts.  For more help, please ask community at [#searxng:matrix.org](https://matrix.to/#/#searxng:matrix.org) .. and open an issue only for a real issue / thanks for understanding.

**Comment by sommerfelddev** [comment]
I'm running into the same issue occasionally, nothing seems odd about my internet connection.

**Comment by Huddeij** [comment]
Yes my inet connection works fine as well while running into this issue occasionally. Self-hosting via docker container 

```yml
services:
  redis:
    container_name: searxng_redis
    image: docker.io/library/redis:alpine
    command: redis-server --save 30 1 --loglevel warning
    networks:
      - searxng
    volumes:
      - redis-data:/data
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    restart: unless-stopped

  searxng:
    container_name: searxng
    image: docker.io/searxng/searxng:latest
    networks:
      - searxng
    ports:
      - 8080:8080
    volumes:
      - ./searxng:/etc/searxng:rw
    environment:
      - SEARXNG_BASE_URL=https://${SEARXNG_HOSTNAME:-localhost}/
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
    restart: unless-stopped

networks:
  searxng:
    ipam:
      driver: default

volumes:
  redis-data:
```
