### ISSUE TITLE
Bug: yacy images engine

### ISSUE THREAD

**Issue by Dalethium** [searxng/searxng#3671]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2024.7.20+657dcb973

**How did you install SearXNG?**

docker

**What happened?**

Using the !yai Start string with the yacy back-end setup only returns page 1. Page 2 does not work.

**How To Reproduce**

Go to page two of any Yacy image search.

**Expected behavior**

Page 2 shows Instead of a parsing error.

**Technical report**

Error
  * Error: json.decoder.JSONDecodeError
  * Percentage: 50
  * Parameters: `('Expecting value',)`
  * File name: `searx/engines/yacy.py:152`
  * Function: `response`
  * Code: `raw_search_results = loads(resp.text)`

**Comment by return42** [comment]
I often have timeout issues, but I can't reproduce a `json.decoder.JSONDecodeError` with the default settings:

https://github.com/searxng/searxng/blob/319afe031e22fb644d336920802dcbafc8a5e338/searx/settings.yml#L2137-L2163

I suppose decode error is related to one of your `base_url` .. whats your setup?

**Comment by Dalethium** [comment]
```
  proxies:
    all://:
      - socks5://redacted:9118
    http://yacy:8090/:
      - ""
  extra_proxy_timeout: 3

engines:
  - name: yacy
    base_url: http://yacy:8090
    disabled: false
    timeout: 30.0
    enable_http: true
  - name: yacy images
    base_url: http://yacy:8090
    disabled: false
    timeout: 30.0
    enable_http: true
```

So my yacy node is hosted locally, which is why I disabled the proxy for that. I will note that so far I've only noticed this when using the !yai Search usage.
