### ISSUE TITLE
/search?q=test&format=json returns forbidden

### ISSUE THREAD

**Issue by realies** [searxng/searxng#3749]

**Comment by vojkovic** [comment]
`- json` needs to be added as a format in the settings https://docs.searxng.org/admin/settings/settings_search.html

Public instances do not allow the json format to prevent abuse.

**Comment by CD1010** [comment]
> `- json` needs to be added as a format in the settings https://docs.searxng.org/admin/settings/settings_search.html
> 
> Public instances do not allow the json format to prevent abuse.

I dont understand.  There is a settings.yaml in the docker repo.  DO i modify that?  Tried does not seem to work

**Comment by realies** [comment]
@CD1010, run

```yml
services:
  redis:
    container_name: redis
    image: docker.io/valkey/valkey:7-alpine
    command: valkey-server --save 30 1 --loglevel warning
    restart: unless-stopped
    user: 1000:1000
    networks:
      - reverse-proxy
    volumes:
      - ./data/valkey-data2:/data
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

  searxng:
    container_name: searxng
    image: docker.io/searxng/searxng:latest
    restart: unless-stopped
    user: 1000:1000
    networks:
      - reverse-proxy
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - ./data/searxng:/etc/searxng:rw
    environment:
      - SEARXNG_BASE_URL=https://${SEARXNG_HOSTNAME:-localhost}/
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
```
then edit `./data/searxng/settings.yml`  and insert this at the bottom:
```
search:
  formats:
    - html
    - json
```
