### ISSUE TITLE
KeyError when YaCy config is not named "yacy"

### ISSUE THREAD

**Issue by LillySchramm** [searxng/searxng#3953]
> Version: `2024.10.19+050451347` (Docker)

It is currently not possible to name a YaCy engine config anything other that `yacy`. It should be possible to do so.

The following config causes said behavior:
```yaml
engines:
  - name: a_name
    engine: yacy
    categories: general
    search_type: text
    base_url:
      - https://search.example.com
    shortcut: ya
    timeout: 4.0
```
```
searxng-1  | 2024-10-21 12:06:23,796 WARNING:searx.engines.ysrv-yacy: ErrorContext('searx/engines/yacy.py', 118, "url = engines['yacy'].base_url  # type: ignore", 'KeyError', None, ()) False
searxng-1  | 2024-10-21 12:06:23,796 ERROR:searx.engines.ysrv-yacy: exception : 'yacy'
searxng-1  | Traceback (most recent call last):
searxng-1  |   File "/usr/local/searxng/searx/search/processors/online.py", line 163, in search
searxng-1  |     search_results = self._search_basic(query, params)
searxng-1  |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
searxng-1  |   File "/usr/local/searxng/searx/search/processors/online.py", line 137, in _search_basic
searxng-1  |     self.engine.request(query, params)
searxng-1  |   File "/usr/local/searxng/searx/engines/yacy.py", line 141, in request
searxng-1  |     params["url"] = f"{_base_url()}/yacysearch.json?{urlencode(args)}"
searxng-1  |                        ^^^^^^^^^^^
searxng-1  |   File "/usr/local/searxng/searx/engines/yacy.py", line 118, in _base_url
searxng-1  |     url = engines['yacy'].base_url  # type: ignore
searxng-1  |           ~~~~~~~^^^^^^^^
searxng-1  | KeyError: 'yacy'
```
When setting `name: yacy`, this issue does not exist.

*I might fix this issue myself at some point*
