### ISSUE TITLE
Favicons sizes are not homogeneous

### ISSUE THREAD

**Issue by jorti** [searxng/searxng#3963]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**

```
2024.10.26+e08ff05ff
``` 

**How did you install SearXNG?**
Container image `docker.io/searxng/searxng:latest`

**What happened?**
After enabling the favicons, the favicons sizes are wildly different for each result, some of them even wider than the whole screen, breaking the page layout and being ugly.

**How To Reproduce**
`favicons.toml`:

```toml
    [favicons]

    cfg_schema = 1   # config's schema version no.

    [favicons.proxy]

    # max_age = 5184000             # 60 days / default: 7 days (604800 sec)

    [favicons.cache]

    db_url = "/var/cache/searxng/faviconcache.db"  # default: "/tmp/faviconcache.db"
    LIMIT_TOTAL_BYTES = 2147483648                 # 2 GB / default: 50 MB
    HOLD_TIME = 5184000                            # 60 days / default: 30 days
    BLOB_MAX_BYTES = 40960                         # 40 KB / default 20 KB
    # MAINTENANCE_MODE = "off"                       # default: "auto"
    # MAINTENANCE_PERIOD = 600                       # 10min / default: 1h
```

`settings.yml`:

```yaml
use_default_settings: true
general:
  instance_name: "SearXNG"
server:
  base_url: https://searchxng.example.com
  secret_key: _not_used_
  limiter: false
  public_instance: false
  method: "GET"
search:
  autocomplete: "duckduckgo"
  favicon_resolver: "duckduckgo"
```

**Expected behavior**
All favicons displayed with the same size (small), next to their search result.

**Screenshots & Logs**

![Captura desde 2024-10-27 09-18-56](https://github.com/user-attachments/assets/1f5b415f-9f17-46ad-acb0-f4880c5e572a)

**Additional context**
