### ISSUE TITLE
Operation not permitted

### ISSUE THREAD

**Issue by sw5ciprl** [searxng/searxng#402]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**

1.0.0-900-6b643e96

**How did you install SearXNG?**

searxng-docker

**What happened?**

A client receives a page with "Internal Server Error". The page does not load.

**How To Reproduce**

Run searxng-docker using docker-compose, add a theme.

**Expected behavior**

No "Internal Server Error" page, everything loads to client properly.

**Screenshots & Logs**

```
searxng    | searx version 1.0.0-900-6b643e96
searxng    | Use existing /etc/searx/uwsgi.ini
searxng    | Use existing /etc/searx/settings.yml
searxng    | Listen on 0.0.0.0:REDACTED
searxng    | [uWSGI] getting INI configuration from /etc/searx/uwsgi.ini
searxng    | [uwsgi-static] added mapping for /static => /usr/local/searx/searx/static
searxng    | [FATAL tini (1)] Unexpected error when forwarding signal: 'Operation not permitted'
```

**Additional context**

I use nginx-proxy for reverse-proxying the engine. Filtron and Morty are functional as well, from searx-docker repo.

**Comment by Zackptg5** [comment]
Same issue here. Set theme to oscar caused issue

**Comment by dalf** [comment]
Looking at https://github.com/krallin/tini/issues/9 , do you have AppArmor installed ?
Can you try to add `privileged: true` to docker-compose.yml:

```yaml
  searxng:
    container_name: searxng
    image: searxng/searxng:latest
    restart: always
    networks:
      - searxng
    command: ${SEARXNG_COMMAND:-}
    volumes:
      - ./searx:/etc/searx:rw
    environment:
      - BIND_ADDRESS=0.0.0.0:8080
      - BASE_URL=https://${SEARXNG_HOSTNAME:-localhost}/
      - MORTY_URL=https://${SEARXNG_HOSTNAME:-localhost}/morty/
      - MORTY_KEY=${MORTY_KEY}
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    privileged: true
```

---
For reference: https://github.com/searx/searx/discussions/2871
