### ISSUE TITLE
Hostnames plugin defaults to off even though it is enabled in the settings.yml

### ISSUE THREAD

**Issue by saukkico** [searxng/searxng#4263]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**

2025.1.29+738906358 

**How did you install SearXNG?**

Docker-compose

**What happened?**

I haven't changed anything in the settings, but suddenly after some recent update the hostnames plugin is disabled even though it has been enabled in the settings.yml this whole time.  I can enable it again by going to settings and toggle the Hostnames plugin on and click save. But then after I click the button to get back the default settings, the hostnames plugin is disabled again.

**How To Reproduce**

Enable the hostnames plugin in settings.yml. Then check the settings page of Searxng and see if the Hostnames plugin is enabled.

**Expected behavior**

Hostnames plugin should be enabled when I enable it in settings.yml

**Screenshots & Logs**

Settings.yml:

```yaml
enabled_plugins:
#   # these plugins are enabled if nothing is configured ..
  - 'Hash plugin'
  - 'Search on category select'
  - 'Self Information'
  - 'Tracker URL remover'
#   - 'Ahmia blacklist'  # activation depends on outgoing.using_tor_proxy
#   # these plugins are disabled if nothing is configured ..
#   - 'Hostname replace'  # see hostname_replace configuration below
  - 'Hostnames plugin'  # see 'hostnames' configuration below
  - 'Basic Calculator'


hostnames:
  replace: # 'rewrite-hosts.yml'
    '(.*\.)?youtube\.com$': 'invidious.example.com'
    '(.*\.)?youtu\.be$': 'invidious.example.com'
    #   '(.*\.)?youtube-noocookie\.com$': 'yotter.example.com'
    '(.*\.)?reddit\.com$': 'farside.link/libreddit'
    '(.*\.)?redd\.it$': 'farside.link/libreddit'
    '(www\.)?twitter\.com$': 'farside.link/nitter'

``` 

Settings in Searxng:

![Image](https://github.com/user-attachments/assets/70e2bbec-8683-4a9a-bb3f-e9ad702ef541)

**Additional context**

**Comment by return42** [comment]
> the hostnames plugin is disabled even though it has been enabled in the settings.yml this whole time. I can enable it again by going to settings and toggle the Hostnames plugin on and click save.

Yes, the behavior changed these days (PR #4183) .. please read my comment:

- https://github.com/searxng/searxng/discussions/4261#discussioncomment-12005310

The question that remain: should we implement a "three state" config for ``default_on``?

If so, we can take this issue as feature request .. otherwise we can close this issue.

**Comment by saukkico** [comment]
Ok, I see what you did there. Thanks for the answer.

I would like to have the 3rd option as well. Let the owner of the instance to choose if the plugin is "opt-in" or "opt-out".

**Comment by 98h398hrpohpoai** [comment]
Would this allow for setting the third option by default in the configs without browser modification?
Only having second option of manually enabling even after setting as default is impractical in a multi-client/user environment.
Particularly for cookieless or other high security/privacy configs.

**Comment by RJGhugo** [comment]
Thanks for the "new feature" request.

I would like to offer "Hostnames plugin" to all user by default.

**Comment by Bnyro** [comment]
> The question that remain: should we implement a "three state" config for default_on?
>
Instance owners can't configure that so I don't think that makes much sense.

If I get it correctly, your change caused plugins to only be visible when `default_on` is set to true AND it's listed in `enabled_plugins`?

I guess in that case we should rather add some more configuration options to `enabled_plugins` to allow switching between `default_on` and `default_off` and completely remove that part from the individual plugins? Such config options are better placed in `settings.yml`.

**Comment by return42** [comment]
> Instance owners can't configure that so I don't think that makes much sense.

When I think about it again, I have to agree with you 🤦 

> I guess in that case we should rather add some more configuration options to `enabled_plugins` to allow switching between `default_on` and `default_off` and completely remove that part from the individual plugins? Such config options are better placed in `settings.yml`.

True, we need a second option in the `settings.yml` and non in the plugin itself.

I think we can extend the `enabled_plugins` similar to something like:

```yaml
enabled_plugins:
  # these plugins are enabled if nothing is configured ..
  - 'Basic Calculator', 'opt-out'
  - 'Hash plugin', 'opt-out'
  - 'Self Information', 'opt-out'
  - 'Tracker URL remover', 'opt-out'
  - 'Unit converter plugin', 'opt-out'
  - 'Ahmia blacklist', 'opt-out'  # activation depends on outgoing.using_tor_proxy
  # these plugins are disabled if nothing is configured ..
  - 'Hostnames plugin', 'opt-in'  
  - 'Open Access DOI rewrite', 'opt-in'
  - 'Tor check plugin', 'opt-in'
```

And with backward compatibility (equal to `opt-out` from above):

```yaml
enabled_plugins:
  - 'Basic Calculator'
  - 'Hash plugin'
  - 'Self Information'
  - 'Tracker URL remover'
  - 'Unit converter plugin'
  - 'Ahmia blacklist'  # activation depends on outgoing.using_tor_proxy
  - 'Hostnames plugin'  
  - 'Open Access DOI rewrite'
  - 'Tor check plugin'
```

Alternative suggestions?

- with backward compatibility to existing `/etc/searxng/settings.yml`

**Comment by Bnyro** [comment]
My idea was similar, but I thought about using a dictionary instead of a list, i.e.
```
- 'Basic Calculator': 'opt-in'
```
to be more user-convenient.

I agree, backward compatibility with the old format is crucial.

**Comment by return42** [comment]
🤔 not sure if a dict is better compared to list.  The config solution should be open for additional features (in the future).

A positional list ..

```py
[
  ['Basic Calculator', "opt-out", ... "<future feature>"],
  ['Tor check plugin', "opt-in", ... "<future feature>"],
]
```

Here is the dict solution you suggested:

```py
[
  {'Basic Calculator': "opt-out", ... "future <key-name>" : "<future feature>"},
  {'Tor check plugin': "opt-in", ... "future <key-name>" : "<future feature>"},
]
```

.. its not clear what "key" is the name of the plugin (take in mind a key/val dict is not positional).

When we prefer a dict over a list, we need something like:

```py
[
  { "name": 'Basic Calculator', "opt" : "out", ... "<future key-name>" : "<future feature>"},
  { "name": 'Tor check plugin': "opt" : "in", ... "<future key-name>" : "<future feature>"},
]
```

alternatively to the two state switch `opt` we can write `opt-out: [true|false]`  .

---

In YAML its a little more verbose :

```yaml
- name: 'Basic Calculator',
  opt: "out"
  <future key-name>: <future feature>
- name: 'Tor check plugin',
  opt: "in"
  <future key-name>: <future feature>
```

.. compared to a positional list:

```yaml
  - 'Basic Calculator', 'opt-out', <future feature>
  - 'Tor check plugin', 'opt-in', <future feature>
```

Not sure what is better .. to be more explicit and flexibility for requests coming up in the future I think a dict is the better choice .. what do you think?
