### ISSUE TITLE
Container unhealthy since adding healthcheck

### ISSUE THREAD

**Issue by foux** [searxng/searxng#4379]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
2025.2.26+887594f63

**How did you install SearXNG?**
Docker

**What happened?**
Since updating to the latest version with Healthchecks, the Sear container is in unhealthy state, preventing it to be accessible via Traefik

**How To Reproduce**
Update to latest docker version

**Expected behavior**
After its starting state, the container should be in `Healthy` status, not `Unhealthy`

**Screenshots & Logs**
```
searxng  | SearXNG version 2025.2.26+887594f63
searxng  | ️Use existing /etc/searxng/uwsgi.ini
redis    | 1:C 26 Feb 2025 08:17:47.188 # WARNING Memory overcommit must be enabled! Without it, a background save or replication may fail under low memory condition. Being disabled, it can also cause failures without low memory condition, see https://github.com/jemalloc/jemalloc/issues/1328. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf a
nd then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
searxng  | ️️️  Checkd new version /etc/searxng/settings.yml.new to make sure SearXNG is working properly
searxng  | Listen on 0.0.0.0:8080
searxng  | [uWSGI] getting INI configuration from /etc/searxng/uwsgi.ini
searxng  | [uwsgi-static] added mapping for /static => /usr/local/searxng/searx/static
searxng  | *** Starting uWSGI 2.0.25.1 (64bit) on [Wed Feb 26 08:30:20 2025] ***
searxng  | ️compiled with version: 13.2.1 20240309 on 17 May 2024 06:11:37
searxng  | os: Linux-6.6.78-Unraid #2 SMP PREEMPT_DYNAMIC Thu Feb 20 13:33:15 PST 2025
searxng  | nodename: 0dd596616d49
searxng  | machine: x86_64
searxng  | clock source: unix
searxng  | ️pcre jit disabled
searxng  | detected number of CPU cores: 16
searxng  | current working directory: /usr/local/searxng
searxng  | detected binary path: /usr/sbin/uwsgi
searxng  | setgid() to 977
searxng  | setuid() to 977
searxng  | chdir() to /usr/local/searxng/searx/
searxng  | your processes number limit is 256637
searxng  | your memory page size is 4096 bytes
searxng  | detected max file descriptor number: 40960
searxng  | building mime-types dictionary from file /etc/mime.types...1390 entry found
searxng  | lock engine: pthread robust mutexes
searxng  | thunder lock: disabled (you can enable it with --thunder-lock)
searxng  | uwsgi socket 0 bound to TCP address 0.0.0.0:8080 fd 3
searxng  | Python version: 3.12.9 (main, Feb  7 2025, 17:40:27) [GCC 13.2.1 20240309]
searxng  | Python main interpreter initialized at 0x15403d76fc30
searxng  | python threads support enabled
searxng  | your server socket listen backlog is limited to 100 connections
searxng  | your mercy for graceful operations on workers is 60 seconds
searxng  | mapped 603360 bytes (589 KB) for 16 cores
searxng  | *** Operational MODE: preforking+threaded ***
searxng  | added /usr/local/searxng/ to pythonpath.
searxng  | spawned uWSGI master process (pid: 7)
searxng  | spawned uWSGI worker 1 (pid: 13, cores: 4)
searxng  | spawned uWSGI worker 2 (pid: 15, cores: 4)
searxng  | spawned 4 offload threads for uWSGI worker 1
searxng  | spawned uWSGI worker 3 (pid: 22, cores: 4)
searxng  | spawned 4 offload threads for uWSGI worker 2
searxng  | spawned uWSGI worker 4 (pid: 27, cores: 4)
searxng  | spawned 4 offload threads for uWSGI worker 3
searxng  | spawned 4 offload threads for uWSGI worker 4
searxng  | WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x15403d76fc30 pid: 15 (default app)
searxng  | WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x15403d76fc30 pid: 13 (default app)
searxng  | WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x15403d76fc30 pid: 27 (default app)
searxng  | WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x15403d76fc30 pid: 22 (default app)
```

**Additional context**
Docker compose : 
```
services:
  redis:
    container_name: redis
    image: docker.io/valkey/valkey:8-alpine
    command: valkey-server --save 30 1 --loglevel warning
    restart: on-failure:5
    networks:
      - searxng
    volumes:
      - ./redis:/data
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
      - DAC_OVERRIDE

  searxng:
    container_name: searxng
    image: docker.io/searxng/searxng:latest
    restart: on-failure:5
    networks:
      - searxng
      - web
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - ./searxng:/etc/searxng:rw
      - ./cache:/var/cache/searxng
    environment:
      - SEARXNG_BASE_URL=https://${SEARXNG_HOSTNAME:-localhost}/
      - UWSGI_WORKERS=${SEARXNG_UWSGI_WORKERS:-4}
      - UWSGI_THREADS=${SEARXNG_UWSGI_THREADS:-4}
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    labels:
      - traefik.enable=true
      - traefik.http.routers.searxng.rule=Host(`my.sear.tld`)
      - traefik.http.routers.searxng.service=searxng
      - traefik.http.services.searxng.loadbalancer.server.port=8080
      - traefik.http.routers.searxng.middlewares=chain-authentik@file

networks:
  searxng:
  web:
    name: web
    external: true
```
