### ISSUE TITLE
Can not get json format using API from a docker container

### ISSUE THREAD

**Issue by PokeLu** [searxng/searxng#4469]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**

Docker image Tag: 2025.3.7-488474750
Installed using docker desktop.

**How did you install SearXNG?**

Installed using a docker compose file as followed: 
```
# version: "3.7"
services:
  searxng:
    container_name: searxng
    image: docker.io/searxng/searxng:latest
    restart: unless-stopped
    networks:
      - open-webui
    ports:
      - "3001:8080" #3001修改为自己想要的端口，8080不可修改
    volumes:
      - ./searxng:/etc/searxng:rw
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - SEARXNG_BASE_URL=http://host.docker.internal:3001 #本机IP:端口，例如192.168.0.231:3001，3001和上面对应一致，后面要用
      - HTTP_PROXY=http://host.docker.internal:7897
      - HTTPS_PROXY=http://host.docker.internal:7897
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

networks:
  open-webui:
    driver: bridge
```

**What happened?**

I was trying to connect my `open-webui` to `searxng`. I enabled json format by:
```
search:
  ···
  # remove format to deny access, use lower case.
  formats: [html, csv, json, rss]
```
I typed in the test url  [http://127.0.0.1:3001/search?q=this+is+a+test+query&format=json](http://127.0.0.1:3001/search?q=this+is+a+test+query&format=json) into my browser on my host machine and I got the json formating result in the brower. However, when I tested it using another container (open-webui container) in the same network by `curl http://host.docker.internal:3001/search?q=this+is+a+test+query&format=json`, I could only get html format response.

**How To Reproduce**

Install using docker desktop and docker-compose.yml as aforementioned.
Change only the formats value in the search part in the default settings.yaml as aforementioned.

**Expected behavior**

**Screenshots & Logs**

![Image](https://github.com/user-attachments/assets/bc27f516-cba0-40be-828d-9bf74036969f)

![Image](https://github.com/user-attachments/assets/466200bd-610c-47cf-af02-5fe4f111efd1)

**Additional context**
