### ISSUE TITLE
simple theme: change the current selection UI

### ISSUE THREAD

**Issue by dalf** [searxng/searxng#448]
**Is your feature request related to a problem? Please describe.**

The current selection:
![image](https://user-images.githubusercontent.com/1594191/139242193-d03d222a-d223-4fe0-8010-b89cc37dcb3a.png)

**Describe the solution you'd like**

Suggestion:
![image](https://user-images.githubusercontent.com/1594191/139242344-2b180c88-e479-4b9c-a468-90949675ef0b.png)

The selection makes a border around the result, which make it more visible.
The arrow is replaced by a left border (this design seems rather common to display a selection). I'm not sure about the color. Perhaps the the width must match the height of the selected category underline.

quick test using the FF dev tools:
```css
.result {
   margin: 0.5rem 0;
   /* Not fixed issue: the padding move the results slightly on the right compare to the current design */
   padding: 1rem;
}

article[data-vim-selected] {
    background: var(--color-result-vim-selected);
    border-left: 0.125rem solid var(--color-result-vim-arrow);
}

/* remove article[data-vim-selected]::before */
```

**Describe alternatives you've considered**

**Additional context**
