### ISSUE TITLE
SearXNG does not start: socket(): Address family not supported by protocol

### ISSUE THREAD

**Issue by bjoernwuest** [searxng/searxng#4507]
**EDIT** by @unixfox: Solution: https://github.com/searxng/searxng/issues/4507#issuecomment-2746476227 and don't disable IPv6: https://github.com/searxng/searxng/issues/4507#issuecomment-2746480694

--------

Docker image: searxng/searxng:latest (pulled on 16.3.2025, 22:00 CET)

Log output:
```
SearXNG  | SearXNG version 2025.3.16+bbb2894b0
SearXNG  | ⚠️  Check new version /etc/searxng/uwsgi.ini.new to make sure SearXNG is working properly
SearXNG  | ⚠️  Check new version /etc/searxng/settings.yml.new to make sure SearXNG is working properly
SearXNG  | Listen on [::]:8080
SearXNG  | [uWSGI] getting INI configuration from /etc/searxng/uwsgi.ini
SearXNG  | [uwsgi-static] added mapping for /static => /usr/local/searxng/searx/static
SearXNG  | *** Starting uWSGI 2.0.25.1 (64bit) on [Mon Mar 17 10:02:42 2025] ***
SearXNG  | compiled with version: 13.2.1 20240309 on 17 May 2024 06:11:37
SearXNG  | os: Linux-6.8.0-51-generic #52-Ubuntu SMP PREEMPT_DYNAMIC Thu Dec  5 13:09:44 UTC 2024
SearXNG  | nodename: 03f64f021bb8
SearXNG  | machine: x86_64
SearXNG  | clock source: unix
SearXNG  | pcre jit disabled
SearXNG  | detected number of CPU cores: 32
SearXNG  | current working directory: /usr/local/searxng
SearXNG  | detected binary path: /usr/sbin/uwsgi
SearXNG  | setgid() to 977
SearXNG  | setuid() to 977
SearXNG  | chdir() to /usr/local/searxng/searx/
SearXNG  | your memory page size is 4096 bytes
SearXNG  | detected max file descriptor number: 1048576
SearXNG  | building mime-types dictionary from file /etc/mime.types...1390 entry found
SearXNG  | lock engine: pthread robust mutexes
SearXNG  | thunder lock: disabled (you can enable it with --thunder-lock)
SearXNG  | socket(): Address family not supported by protocol [core/socket.c line 82]
```

Docker config:
```
  searxng:
    container_name: SearXNG
    image: docker.io/searxng/searxng:latest
    restart: unless-stopped
    volumes:
      - /docker/searxng:/etc/searxng:rw
    environment:
      - SEARXNG_BASE_URL=https://myhost.mydomain.tld/
      - SEARXNG_REDIS_URL=redis://searxng-redis:6379
      - SEARXNG_API_KEY=<something>
      - SEARXNG_QUERY_URL="https://myhost.mydomain.tld/search?q=<query>"
      - ENABLE_RAG_WEB_SEARCH=true
      - RAG_WEB_SEARCH_ENGINE=searxng
      - RAG_WEB_SEARCH_RESULT_COUNT=50
      - RAG_WEB_SEARCH_CONCURRENT_REQUESTS=5
      - SEARXNG_LIMITER=false
      - UWSGI_WORKERS=8
      - UWSGI_THREADS=8
      - SEARXNG_DEBUG=true
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    depends_on:
      searxng-redis:
        condition: service_healthy
```

**Comment by bjoernwuest** [comment]
Could trace the issue back to all of 2025.3 ; latest docker image working is 2025.2.28-355883f36

**Comment by return42** [comment]
Really 355883f36 ? .. can't believe [typer](https://typer.tiangolo.com/) is responsible for ...

```
SearXNG  | socket(): Address family not supported by protocol [core/socket.c line 82]
```

Not sure the issue is really related to SearXNG .. can you give us a debug log from SearXNG?

**Comment by unixfox** [comment]
Probably related to the latest changes around ipv6.

Stackoverflow suggest that you probably have disabled ipv6 entirely on the host: https://stackoverflow.com/a/67307177

If so you enable it back or change the bind address to 0.0.0.0

**Comment by unixfox** [comment]
Closing as it's probably that.

**Comment by ghost** [comment]
Did you get this problem fixed? I tried both bind_address: "0.0.0.0" in settings.yml and setting the environment variable SEARXNG_BIND_ADDRESS=0.0.0.0 but the error remains.

**Comment by unixfox** [comment]
It's BIND_ADDRESS

https://github.com/searxng/searxng/blob/5986629c6bfe0fd800f30913f59b2cc43c9e58b6/dockerfiles/docker-entrypoint.sh#L17

**Comment by RichyHBM** [comment]
I've tried the following with no luck, I dont expose ports as I just use traefik as a reverse proxy

```
      - INSTANCE_NAME=searxng
      - BIND_ADDRESS=0.0.0.0:8888
      - SEARXNG_PORT=8888
      - SEARXNG_BIND_ADDRESS=0.0.0.0 
```

As far as I am aware IPv6 is enabled on my server though not used

**Comment by bjoernwuest** [comment]
I use Nginx Proxy Manager as proxy and my SearXNG container does not expose any ports. I tried those four env variables but no success:

1) - BIND_ADDRESS=0.0.0.0
2) - BIND_ADDRESS=127.0.0.1
3) - SEARXNG_BIND_ADDRESS=0.0.0.0
4) - SEARXNG_BIND_ADDRESS=127.0.0.1

I am running on February release, which works. So I think it may be (a) a new "feature" introduced by SearXNG or its dependencies introduced since then, or (b) any incompatibility between "latest" docker and SearXNG or its dependencies. Yet, since the logs - even in Debug-mode, are not that talkative when it comes to the socket, I cannot tell what may be the reason.

**Comment by ghost** [comment]
> It's BIND_ADDRESS
> 
> [searxng/dockerfiles/docker-entrypoint.sh](https://github.com/searxng/searxng/blob/5986629c6bfe0fd800f30913f59b2cc43c9e58b6/dockerfiles/docker-entrypoint.sh#L17)
> 
> Line 17 in [5986629](/searxng/searxng/commit/5986629c6bfe0fd800f30913f59b2cc43c9e58b6)
>    BIND_ADDRESS  uwsgi bind to the specified TCP socket using HTTP protocol.

I can confirm this fixes the issue!

**Comment by RichyHBM** [comment]
What was the exact value you used? See above the value I tried and it didn't fix it

**Comment by ghost** [comment]
I set BIND_ADDRESS=0.0.0.0:8080 as an environment variable in docker-compose and it now starts up without errors.

**Comment by bjoernwuest** [comment]
Ok, tried again with BIND_ADDRESS=0.0.0.0 and latest pull from docker. Now, it does not complain about the socket() error, but the container is not reachable from any port. So, I also added BIND_PORT=8080 but still the container is not reachable from anywhere within docker or from the outside.
Thus, I will still stay on 2025.2.28-355883f36 which works.

**Comment by bjoernwuest** [comment]
Ok, tried a bit more and BIND_ADDRESS=0.0.0.0:8080 works. The respective hint could be found in docker_entrypoint.sh, where uwsgi uses just ${BIND_ADDRESS} and ignores ${BIND_PORT} :).

**Comment by RichyHBM** [comment]
Hmm, I'm not sure whats going on with mine then, still wont work on latest.

This is my compose
```
---
services:
  searxng:
    image: searxng/searxng #:2025.3.15-583007fd0
    container_name: searxng
    networks:
      - traefik_reverse_proxy
    env_file:
      - ${COMPOSE_INCLUDE_PATH:-../common/}base.env
    environment:
      - BASE_URL=https://searxng.my.domain/
      - INSTANCE_NAME=searxng
      - BIND_ADDRESS=0.0.0.0:8080
      - SEARXNG_PORT=8080
      - SEARXNG_BIND_ADDRESS=0.0.0.0
    volumes:
      - ${COMPOSE_STORAGE_LOCATION:-./storage/}searxng:/etc/searxng
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.services.searxng.loadbalancer.server.port=8080
      - traefik.http.services.searxng.loadbalancer.server.scheme=http
```

The env file contains
```
PUID=1000
PGID=1000
HOST_USER_GID=${PUID}
HOST_USER_ID=${PGID}
USER_ID=${PUID}
GROUP_ID=${PGID}
UID=${PUID}
GID=${PGID}

TIMEZONE=UTC
PHP_TZ=UTC
TZ=UTC

NODE_ENV=production
LOG_LEVEL=info
```

**Comment by ghost** [comment]
@RichyHBM Make sure your settings.yml or uwsgi.ini aren't overriding your environment variables by setting a bind address, and try removing SEARXNG_PORT/SEARXNG_BIND_ADDRESS. I guess its also possible you're running into an unrelated issue.

**Comment by unixfox** [comment]
Instead of using `BIND_ADDRESS`, you guys should check:
- running latest docker version (works on 27 or 28)
- ipv6 is activated on the host
   - `cat /proc/sys/net/ipv6/conf/*/disable_ipv6` always returns 0
   - `ipv6.disable=1` is not added in the grub config

I just installed Docker using https://get.docker.com/, then I launched searxng with `docker run -p 8080:8080 searxng/searxng:latest` and that worked great.

**Comment by ghost** [comment]
> Instead of using `BIND_ADDRESS`, you guys should check:
> 
>     * running latest docker version (works on 27 or 28)
> 
>     * ipv6 is activated on the host
>       
>       * `cat /proc/sys/net/ipv6/conf/*/disable_ipv6` always returns 0
>       * `ipv6.disable=1` is not added in the grub config
> 
> 
> I just installed Docker using https://get.docker.com/, then I launched searxng with `docker run -p 8080:8080 searxng/searxng:latest` and that worked great.

I think most of us are here because we have by choice disabled ipv6 on the host and are looking for a workaround, which thankfully there was!

**Comment by unixfox** [comment]
@broizter Don't disable IPv6, it's bad. Try to find solutions for why ipv6 may cause you some issues. There are always some solutions that doesn't involve disabling ipv6, join our [matrix](https://matrix.to/#/#searxng:matrix.org) or [IRC](https://web.libera.chat/?channel=#searxng) I'll be happy to give you some if you explain there why you disabled IPv6 in the first place.

By disabling IPv6, you aren't doing any favor to the internet. There are no public IPv4 addresses anymore: https://en.wikipedia.org/wiki/IPv4_address_exhaustion and it's bad for the progress of the internet, we need to all move to IPv6.

If we have people like you that disable IPv6, how are we going to fix that major issue with the internet... It's becoming more and more costly to use IPv4 for running services on the internet: https://ipv4.global/blog/ipv4-address-prices/

**Comment by RichyHBM** [comment]
So trying the following, these are the logs

```
services:
  searxng:
    image: searxng/searxng #:2025.3.15-583007fd0
    container_name: searxng
    networks:
      - traefik_reverse_proxy
    env_file:
      - ${COMPOSE_INCLUDE_PATH:-../common/}base.env
    environment:
      - BASE_URL=https://searxng.my.domain/
      - INSTANCE_NAME=searxng
      - BIND_ADDRESS=0.0.0.0:8080
      #- SEARXNG_PORT=8080
      #- SEARXNG_BIND_ADDRESS=0.0.0.0
    volumes:
      - ${COMPOSE_STORAGE_LOCATION:-./storage/}searxng:/etc/searxng
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.services.searxng.loadbalancer.server.port=8080
      - traefik.http.services.searxng.loadbalancer.server.scheme=http
```
The only mounted file is the limiter.toml file from the docker git repo

```
searxng  | SearXNG version
searxng  | Create /etc/searxng/uwsgi.ini
searxng  | Create /etc/searxng/settings.yml
searxng  | Listen on 0.0.0.0:8080
searxng  | [uWSGI] getting INI configuration from /etc/searxng/uwsgi.ini
searxng  | [uwsgi-static] added mapping for /static => /usr/local/searxng/searx/static
searxng  | *** Starting uWSGI 2.0.25.1 (64bit) on [Sun Mar 23 21:51:47 2025] ***
searxng  | compiled with version: 13.2.1 20240309 on 17 May 2024 06:11:37
searxng  | os: Linux-6.1.0-32-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.129-1 (2025-03-06)
searxng  | nodename: 266fcba0ed8e
searxng  | machine: x86_64
searxng  | clock source: unix
searxng  | pcre jit disabled
searxng  | detected number of CPU cores: 6
searxng  | current working directory: /usr/local/searxng
searxng  | detected binary path: /usr/sbin/uwsgi
searxng  | setgid() to 977
searxng  | setuid() to 977
searxng  | chdir() to /usr/local/searxng/searx/
searxng  | your memory page size is 4096 bytes
searxng  | detected max file descriptor number: 1048576
searxng  | building mime-types dictionary from file /etc/mime.types...1390 entry found
searxng  | lock engine: pthread robust mutexes
searxng  | thunder lock: disabled (you can enable it with --thunder-lock)
searxng  | uwsgi socket 0 bound to TCP address 0.0.0.0:8080 fd 3
searxng  | Python version: 3.12.9 (main, Feb  7 2025, 17:40:27) [GCC 13.2.1 20240309]
searxng  | Python main interpreter initialized at 0x7f033e24dc30
searxng  | python threads support enabled
searxng  | your server socket listen backlog is limited to 100 connections
searxng  | your mercy for graceful operations on workers is 60 seconds
searxng  | mapped 844704 bytes (824 KB) for 24 cores
searxng  | *** Operational MODE: preforking+threaded ***
searxng  | added /usr/local/searxng/ to pythonpath.
searxng  | spawned uWSGI master process (pid: 7)
searxng  | spawned uWSGI worker 1 (pid: 15, cores: 4)
searxng  | spawned uWSGI worker 2 (pid: 17, cores: 4)
searxng  | spawned 4 offload threads for uWSGI worker 1
searxng  | spawned 4 offload threads for uWSGI worker 2
searxng  | spawned uWSGI worker 3 (pid: 25, cores: 4)
searxng  | spawned 4 offload threads for uWSGI worker 3
searxng  | spawned uWSGI worker 4 (pid: 30, cores: 4)
searxng  | spawned uWSGI worker 5 (pid: 31, cores: 4)
searxng  | spawned 4 offload threads for uWSGI worker 4
searxng  | spawned uWSGI worker 6 (pid: 36, cores: 4)
searxng  | spawned 4 offload threads for uWSGI worker 6
searxng  | spawned 4 offload threads for uWSGI worker 5
searxng  | WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x7f033e24dc30 pid: 25 (default app)
searxng  | WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x7f033e24dc30 pid: 30 (default app)
searxng  | WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x7f033e24dc30 pid: 36 (default app)
searxng  | WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x7f033e24dc30 pid: 15 (default app)
searxng  | WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x7f033e24dc30 pid: 31 (default app)
searxng  | WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x7f033e24dc30 pid: 17 (default app)
```
