### ISSUE TITLE
dokuwiki basedir duplication

### ISSUE THREAD

**Issue by grasdk** [searxng/searxng#4598]
**Version of SearXNG**
2025.3.17+885d02c8c

**How did you install SearXNG?**
searxng-docker

**What happened?**
Enabled the dokuwiki engine and configured it to connect to my dokuwiki instance. My dokuwiki runs at
`http://my.dockerhost.lan/dokuwiki` behind Caddy2 reverse proxy.

Dokuwiki's `basedir` value is  `/dokuwiki/`. Dokuwiki works in all aspects.

dokuwiki search delivers results, but the URL (link) has double `dokuwiki` in the path:
`http://my.dockerhost.lan/dokuwiki/dokuwiki/pageid`

I assume this is because the dokuwiki `basedir` added to the searxng engine's `basepath` (see context below)

**How To Reproduce**

1. Run dokuwiki as described here: https://docs.linuxserver.io/images/docker-dokuwiki/
2. Run behind reverse proxy, e.g. Caddy2, letting it be exposed as `<hostname>/dokuwiki`
3. Configure dokuwiki with basedir `/dokuwiki/` (as dokuwiki will not autodetect a reverse proxy in a container)
4. Restart dokuwiki container and test that it works
5. Configure searxng engine:
    ```
      - name: dokuwiki
        engine: doku
        shortcut: dowi
        base_url: 'http://my.dockerhost.lan/dokuwiki'
        enable_http: True
        timeout: 10.0
    ```
6. Start searxng and use the engine to search for something you have in your wiki.

**Expected behavior**
Only a single `/dokuwiki` in the URL / link in the searxng results.

**Screenshots & Logs**

![Image](https://github.com/user-attachments/assets/fa94f9d3-3bb9-4354-bb07-a4ec24f438de)

![Image](https://github.com/user-attachments/assets/f35286f9-50cf-4d24-99fd-179daeb25b71)

**Additional context**

I tried to remove `/dokuwiki` from `base_url`, but then there was no connection to the search API.

If `/dokuwiki/` is removed from `basedir` in dokuwiki, dokuwiki itself does not work properly.

**Comment by grasdk** [comment]
Thanks :)

**Comment by grasdk** [comment]
For anyone who might stumble on this in the future. As an alternative to the above engine, you can define a dokuwiki engine using the json_engine. _Why? Ability to show some content in the search result in searxng, from the "snippet" value of dokuwiki results._

Here is a jinja2 template for it:

```
  - name: dokuwiki
    engine: json_engine
    shortcut: dowi
    enable_http: True
    timeout: 10.0
    method: POST
    headers:
      Authorization: Bearer {{dokiwiki_authtoken}}
      Content-Type: application/json
    search_url: {{dokuwiki_base_url}}/lib/exe/jsonrpc.php/core.searchPages
    request_body: >-{% raw %}
      {{
        "query": "{query}"
      }}
{% endraw %}
    results_query: result
    url_query: id
    url_prefix: {{dokuwiki_base_url}}/
    title_query: title
    content_query: snippet
    content_html_to_text: true
    paging: False
```

I use jinja2, because I already use Ansible to insert the template into the correct place in searxng's `settings.yml`. So it is a small matter to also inject values for `{{dokiwiki_authtoken}}` and `{{dokuwiki_base_url}}`.

If you just want to copy/paste, you need to change 4 things in the above:

1. Replace `{{dokiwiki_authtoken}}` with the token in your dokuwiki profile (documented [here](https://www.dokuwiki.org/devel:authentication)).
2. Replace BOTH occurences of `{{dokuwiki_base_url}}` with your dokuwiki base url, e.g. `http://example.com/dokuwiki`
3. Remove `{% raw %}` (keep the newline and carriage return)
4. Remove `{% endraw %}` (remove the whole line)

Example with **fake token** and **fake dokuwiki base url**:

```
  - name: dokuwiki
    engine: json_engine
    shortcut: dowi
    enable_http: True
    timeout: 10.0
    method: POST
    headers:
      Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.FAKEPAYLOAD4TESTING.4b4df00dbadc0ffee1234567890abcdef
      Content-Type: application/json
    search_url: http://example.com/dokuwiki/lib/exe/jsonrpc.php/core.searchPages
    request_body: >-
      {{
        "query": "{query}"
      }}
    results_query: result
    url_query: id
    url_prefix: http://example.com/dokuwiki/
    title_query: title
    content_query: snippet
    content_html_to_text: true
    paging: False
```
