### ISSUE TITLE
Bug: Latest container not working

### ISSUE THREAD

**Issue by Drikanis** [searxng/searxng#4718]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**

Docker container tag:
`searxng/searxng:latest@sha256:46745cb5e69796fc601c17b2c4dc34351341203e15ada46ecae100bfe050e42a`

Cannot determine application commit id because it will not load.

**How did you install SearXNG?**

Docker deployed in kubernetes cluster, issue reproducible with only docker.

**What happened?**

On upgrade to the image listed above, the container would not start up at all because uwsgi.ini could not be found. After finding the new location of the file in the container and setting `UWSGI_SETTINGS_PATH=/usr/local/searxng/dockerfiles/uwsgi.ini`, the container would start and appear to start listening but would not respond to any requests, timing out the gateway instead.

**How To Reproduce**

You can reproduce this just with docker:
```
docker run --rm -p 8080:8080 -e UWSGI_SETTINGS_PATH=/usr/local/searxng/dockerfiles/uwsgi.ini searxng/searxng:latest@sha256:46745cb5e69796fc601c17b2c4dc34351341203e15ada46ecae100bfe050e42a
```
Browsing to http://localhost:8080 eventually just times out as the application doesn't respond.

**Expected behavior**

Application should function.

**Screenshots & Logs**

```
SearXNG version 2025.5.4+2e74d8632
Use existing /usr/local/searxng/dockerfiles/uwsgi.ini
Use existing /etc/searxng/settings.yml
Listen on [::]:8080
[uWSGI] getting INI configuration from /usr/local/searxng/dockerfiles/uwsgi.ini
[uwsgi-static] added mapping for /static => /usr/local/searxng/searx/static
*** Starting uWSGI 2.0.29 (64bit) on [Mon May  5 02:02:23 2025] ***
compiled with version: 12.2.0 on 04 May 2025 20:34:43
os: Linux-6.1.0-31-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.128-1 (2025-02-07)
nodename: searx-698fcbfd7f-689jg
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 12
current working directory: /usr/local/searxng
detected binary path: /usr/local/searxng/venv/bin/uwsgi
chdir() to /usr/local/searxng/searx/
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
building mime-types dictionary from file /etc/mime.types...1545 entry found
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP6 address [::]:8080 fd 3
Python version: 3.13.3 (main, Apr 28 2025, 22:13:21) [GCC 12.2.0]
Python main interpreter initialized at 0x7f85965a3a70
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
*** Operational MODE: no-workers ***
added /usr/local/searxng/ to pythonpath.
spawned uWSGI master process (pid: 1)
```

**Additional context**

**Comment by Drikanis** [comment]
Looks like this is due to env vars having their defaults removed in https://github.com/searxng/searxng/commit/2e74d863210c0d21b9e0a64576dcd24237f23f8c

To get everything working, I had to manually set:
```bash
UWSGI_SETTINGS_PATH=/usr/local/searxng/dockerfiles/uwsgi.ini #the new location of the default uwsgi.ini file inside the container
UWSGI_WORKERS=12 #my number of CPUs
UWSGI_THREADS=4 #the old default
```

**Comment by CXwudi** [comment]
I am also facing permission denied issue for just bring up a brand new container, here is the reproducible compose file:

```yml
  searxng:
    image: searxng/searxng:latest # currently the dockerfile is buggy due to non-root change, wait until fix    # see https://github.com/searxng/searxng/commit/2e74d863210c0d21b9e0a64576dcd24237f23f8c
    container_name: lobechat-searxng
    restart: unless-stopped
    volumes:
      # make sure to add json format
      - searxng-data:/etc/searxng
    environment:
      - SEARXNG_BIND_ADDRESS='0.0.0.0'
      - SEARXNG_PORT=8080
    networks:
      - default
    ports: 
      - 8080:8080
    healthcheck:
      test: ["CMD-SHELL", "wget -O /dev/null http://127.0.0.1:8080/ || exit 1"]
      interval: 2s
      timeout: 5s
      retries: 10
```

switching version before https://github.com/searxng/searxng/commit/2e74d863210c0d21b9e0a64576dcd24237f23f8c introduced like `searxng/searxng:2025.5.3-8ef5fbca4` would work
