### ISSUE TITLE
change path configuration

### ISSUE THREAD

**Issue by killforby** [searxng/searxng#4818]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**

**How did you install SearXNG?**

**What happened?**

**How To Reproduce**

**Expected behavior**

**Screenshots & Logs**

![Image](https://github.com/user-attachments/assets/2496576c-ebdd-49cc-9289-ad20d16c19b2)

**Additional context**

sed: bad option in substitution expression
SearXNG 2025.5.20+7420706
...
... INFORMATION
... Update available for "/etc/searxng/uwsgi.ini"
... It is recommended to update the configuration file to ensure proper functionality
...
... New version placed at "/etc/searxng/uwsgi.ini.new"
... Please review and merge changes
...
...
... INFORMATION
... Update available for "/etc/searxng/settings.yml"
... It is recommended to update the configuration file to ensure proper functionality
...
... New version placed at "/etc/searxng/settings.yml.new"
... Please review and merge changes
...

**Comment by ShadowPeo** [comment]
Can confirm here too, getting permission errors after removing the files to try and let it start again from scratch as well.

Testing with world writable permissions on config folder (./searxng in my case) still elicits the same errors

Reverting to image 2025.5.18-5dff826 resolves the issue

**Comment by Roomba5** [comment]
same

**Comment by Drikanis** [comment]
I worked around it by bypassing the entrypoint script altogether. My k8s deployment now just calls uwsgi directly with the appropriate config files and environment variables set.

Trying to modify any config file is guaranteed to fail on k8s deployments that pass in configuration files via read-only mounted configmaps or secrets.

**Comment by inetol** [comment]
If you change the [*default path*](https://github.com/searxng/searxng/blob/7420706a5074803a78f3c795cf79427746e504e0/container/base.yml#L34) of the configuration volume you must also modify its ENV `CONFIG_PATH` using the absolute path, this has been set to help maintain ownership consistency for the entire volume on custom locations.

Related https://github.com/searxng/searxng/issues/4802

**Comment by systemofapwne** [comment]
Same issue here


<details>

<summary>Excerpt of my compose file</summary>

```yaml
  redis:
    hostname: redis
    image: "redis:alpine"
    command: redis-server --save "" --appendonly "no"
    restart: always
    networks:
      - searx
    tmpfs:
      - /var/lib/redis
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    #Resources limits
    mem_limit: 512m
    mem_reservation: 32m
    cpus: 0.5
    pids_limit: 100

  searx:
    hostname: searxng
    image: searxng/searxng:latest
    #ports:
    #  - "1777:8080"
    restart: always
    volumes:
      - /home/searx:/etc/searxng:rw
    env_file: searx.env
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
    # Enforce external DNS (do not rely on our internal DNS for resolving upstream search engines. Otherwise, timeouts might happen if our dns upstream resolvers are unreachable)
    dns:
      - 1.1.1.1
      - 1.0.0.1
    #Resources limits
    mem_limit: 2048m
    mem_reservation: 512m
    cpus: 4
    pids_limit: 1000
    networks:
      searx: null
      static:
          ipv4_address: 10.2.0.106
```

Env file only has `SEARXNG_BASE_URL` set, nothing else.
</details>
