### ISSUE TITLE
SearXNG 2025.5.20+7420706  cp: can't create '/etc/searxng/uwsgi.ini.new': File exists

### ISSUE THREAD

**Issue by xknex** [searxng/searxng#4823]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
<!-- If you are running on master branch using git execute this command
in order to fetch the latest commit ID: SearXNG 2025.5.20+7420706

**How did you install SearXNG?**

This is my docker-compose.yaml
```
services:
  redis:
    container_name: redis
    image: docker.io/valkey/valkey:8-alpine
    command: valkey-server --save 30 1 --loglevel warning
    restart: unless-stopped
    networks:
      - searxng
    volumes:
      - valkey-data:/data
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    logging:
      driver: "json-file"
      options:
        max-size: "4m"
        max-file: "1"
  searxng:
    container_name: searxng
    image: docker.io/searxng/searxng:latest
    restart: unless-stopped
    networks:
      - searxng
    ports:
      - "8181:8080" #change 8181 as needed, but not 8080
    volumes:
      - searxng:/etc/searxng:rw
    environment:
      - SEARXNG_BASE_URL=http://192.168.178.45:8181 #Change "your.docker.server.ip" to your Docker server's IP
      - UWSGI_WORKERS=4 #You can change this
      - UWSGI_THREADS=2 #You can change this
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    logging:
      driver: "json-file"
      options:
        max-size: "4m"
        max-file: "1"
networks:
  searxng:
volumes:
  valkey-data: #redis storage
  searxng: #searxng storage
```

**What happened?**
After startup the container only prints the above shown error message to log and the web interface does not respond (connection refused)

**How To Reproduce**
Use the above mentioned compose file and start the stack (redis + searxng), check container logs.

**Expected behavior**
SearxNG web interface working as usual.

**Screenshots & Logs**
All relevant log is in the issue title.
