### ISSUE TITLE
Healthcheck port is hardcoded to 8080, not the server port or bind address

### ISSUE THREAD

**Issue by FutureDouble** [searxng/searxng#4906]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**

2025.6.9+d0bb977

**How did you install SearXNG?**

using the docker image `docker.io/searxng/searxng:latest`

**What happened?**

Healthcheck is unhealthy, unless changed with

```yaml
  healthcheck:
    test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:9003/healthz"]
    interval: 30s
    timeout: 10s
    retries: 3
```

9003 is my server port.

**How To Reproduce**

use a custom port with

```yaml
environment:
  - BIND_ADDRESS=0.0.0.0:9003
```

or 

```yml
server:
  port: 9003
```

**Expected behavior**

Healthcheck should be on the same port as the configured port or bind address.
