### ISSUE TITLE
tabs don't act like tabs without JavaScript

### ISSUE THREAD

**Issue by return42** [searxng/searxng#498]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**

https://github.com/searxng/searxng/commit/7a9dda

**How did you install SearXNG?**

    make run

**What happened?**

There is a "click on the .."  text direct under the categories

![grafik](https://user-images.githubusercontent.com/554536/141643149-78d5944c-3598-4865-830a-6a6cd9da5872.png)

**How To Reproduce**

~It is very strange:~ The issue appears when I enable plugins / see https://github.com/searxng/searxng/issues/498#issuecomment-968061989 and 6debda2 :

```yaml
enabled_plugins:
  - "Hostname replace"  # see configuration below

# "Hostname replace" plugin configuration example:
hostname_replace:
    'spam\.example\.com':             false  # remove results from spam.example.com
```
---

**Another issue I observe since  7a9dda**

There is a line break in the category column that overlaps in the column size of the table layout ..

![grafik](https://user-images.githubusercontent.com/554536/141643291-8b1323b4-baac-4bf1-b441-2adcf7c0710b.png)
