### ISSUE TITLE
Terminology: Disambiguate "engine"

### ISSUE THREAD

**Issue by not-my-profile** [searxng/searxng#631]
SearXNG currently uses the word "engine" to refer to two distinct things:

* an actual search engine (e.g. wiktionary)
* the Python module that implements support for the engine (e.g. mediawiki, xpath, json_engine, etc.)

This is best exemplified by `settings.yml` which reads:

```yaml
engines:
  - name: apk mirror
    engine: apkmirror
    timeout: 4.0
    shortcut: apkm
    disabled: true
```

Notice how the engine has an engine? The same ambiguity can of course also be observed in the documentation:

![illustration](https://user-images.githubusercontent.com/73739153/146933722-893f509b-2e04-4e7f-9d10-de336552c577.png)

 I believe that this is bound to confuse users and therefore propose that we introduce clear terminology, for example by using:

* "engine" to refer to a search engine configured in `settings.yml`
* "client" to refer to the Python module powering the engine support.

Then documentation could for example say:

> Every search engine configured in `settings.yml` is powered by a client. While some engines have a dedicated client (e.g. the `google` client is only used for the Google search engine), other clients (e.g. the `xpath` client) power many engines.

This would entail:

* Updating the `settings.yml` handler to support the `client` engine property. For backwards compatibility we could still support the `engine` property. Specifying both for the same engine would result in a configuration error.
* Updating the documentation to always use the correct terms.
* Renaming `json_engine` to `json_client` (ideally in a backwards compatible manner with a deprecation warning?).
* Renaming `searx/engines/` to `searx/clients/`.
* Renaming `configured_engines.rst` back to `engines.rst`.

What do you think?

**Comment by return42** [comment]
> "client" to refer to the Python module powering the engine support.

my 5cent: lets use "engine type" in the documentation and avoid renaming the implementations to `client*`.

**Comment by not-my-profile** [comment]
>lets use "engine type"

I'm afraid we already have `engine_type` and that's yet another thing (whether an engine is `online`, `offline`, `online_currency` or `online_dictionary`). (Besides "type" is not really a good name for a piece of code.)

**Comment by return42** [comment]
> Besides "type" is not really a good name for a piece of code

OT: why? .. classes are often named as *types* 

> I'm afraid we already have engine_type and that's yet another thing  ...

Since this piece of code is always a module, what about "Engine Module" in the documentation?

**Comment by not-my-profile** [comment]
>> Besides "type" is not really a good name for a piece of code
>
> OT: why? .. classes are often named as types

A module contains code, a type does not contain code. (Besides in Python modules are objects instead of classes).

> Since this piece of code is always a module, what about "Engine Module" in the documentation?

That's a good idea! And does indeed spare us from renaming `searx.engines` / `json_engine`.

I would still however prefer
```yaml
engines:
  - name: apk mirror
    module: apkmirror
```

over

```yaml
engines:
  - name: apk mirror
    engine: apkmirror
```

**Comment by return42** [comment]
> A module contains code, a type does not contain code.

Depends on the OOP model.

> Besides in Python modules are objects instead of classes

We use a engine module as "namespace", we add names to (e.g. supported_languages).

> I would still however prefer

@dalf what do you think, should we rename property 'engine' to 'module' .. what will we do about backward compatibility .. I want to avoid to much "backward compatibility" code just while a name could be disambiguate.

**Comment by dalf** [comment]
I like the `module: apkmirror` in settings.yml

> what will we do about backward compatibility .. I want to avoid to much "backward compatibility" code just while a name could be disambiguate.

Yes, I agree.

However, if we go into that direction `searx/settings_defaults.py` can ease that: it can translate the old format in the new format.

Note: the engines section of settings.yml has some legacies:
* this is a unordered list of engines, but actually the `name` [has to be unique](https://github.com/searxng/searxng/blob/56f68a1c29f0639da35aedefc5d7083f4c3da496/searx/engines/__init__.py#L241-L244). So why not make declare the engines as an yaml dictionary ?
* the shortcut has to be unique too. But, IMO, there is a valid request to have multiple values : https://github.com/searx/searx/issues/2229
* for legacy reason, the network configuration can be either:
  ```yaml
  - name: apkmirror
    engine: apkmirror
    proxies:
        - all://: socks5h://127.0.0.1:1337
  ```
  
  or
  ```yaml
  - name: apkmirror
    engine: apkmirror
    network:
        proxies:
            - all://: socks5h://127.0.0.1:1337
  ```
  the first version is the legacy one: in this case, there is a `proxies` global variable in the scope of the Python module `searx.engines.apkmirror`
  
  
To sum up, a new format can be:
```yaml
engines:
  yahoo:
    module: yahoo   # here we can image that somepackage.somemodule could be valid to load module outside of searx.engines.* scope. The name module makes even more sense in this case.
    shortcuts:
        - yh
        - ㄱ
    network:
        proxies:
            - all://: socks5h://127.0.0.1:1337	  
```

I'm sure it raises multiple questions and this is out of topic regarding this issue.

So, what I suggest:
* not to change settings.yml format only for engine -> module
* start to think about a new settings.yml format (_perhaps_ related to #534 ). From that we can think how to deal with the two formats (either write two loaders or a migration tool, or ...). We will have to deal with backward compatibility once but it will make settings.yml more readable.
