### ISSUE TITLE
"onions" category broken

### ISSUE THREAD

**Issue by tiekoetter** [searxng/searxng#643]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
6fb6e8c22acda9adf4fcbb5d0665243a9edf336e

**How did you install SearXNG?**
https://searxng.github.io/searxng/admin/installation.html

**What happened?**
When I tried to add torch (tch) to my SearXNG instance in settings.yml the "onions" category didn't appear. The engine itself could also not be used with `!tch test`.
When I renamed the category to something different (e.g. "onion") in settings.yml it appeard in the categories list in SearXNG and the engine was working.

**How To Reproduce**
- Install SearXNG
- Setup TOR socks5 proxy
- Add torch to settings.yml

```
  - name: torch
    engine: xpath
    paging: true
    search_url:
      http://xmh57jrknzkhv6y3ls3ubitzfqnkrwxhopf5aygthi7d6rplyvk3noyd.onion/cgi-bin/omega/omega?P={query}&DEFAULTOP=and
    results_xpath: //table//tr
    url_xpath: ./td[2]/a
    title_xpath: ./td[2]/b
    content_xpath: ./td[2]/small
    categories: onions
    proxies:
      all://: 
        - socks5h://127.0.0.1:9050
    using_tor_proxy: true
    enable_http: true
    shortcut: tch
    disabled: true
```
- Make a search with `!tch test`

**Expected behavior**
Onion category appearing in the categories list and engine working correctly when using `!tch test`.

**Additional context**
I am also not sure what `using_tor_proxy: true` exactly does.

I renamed the `categories: onions` to `categories: onion` which made the engines available.
~~This temporary fix is active on my instance https://searx.tiekoetter.com~~
I changed how `using_tor_proxy` is handled. See https://github.com/tiekoetter/searxng/commit/b84acb7e8d5d0c0fcaf1dc751bb3195b3fd5d1c8 for reference.
