### ISSUE TITLE
[question] Having troubles to setup the env settings of searxng in my docker-compose

### ISSUE THREAD

**Issue by ghost** [searxng/searxng#656]
Hi,
i'm currently trying to set things in my docker-compose like that :

```
version: "3.9"

services:
  searxng:
    image: searxng/searxng:latest
    restart: always
    ports:
      - "127.0.0.1:8080:8080"
    command: ${SEARX_COMMAND:-}
    volumes:
      - link:/etc/searxng:rw
      - link:/etc/searx
      - link:/var/log/uwsgi
    environment:
     DEBUG: "false"
     INSTANCE_NAME: "SEARXNG (CURRENTLY IN TEST)"
     ENABLE_STATS: "false"
     SAFE_SEARCH: "0"
     PORT: "8080"
     BIND_ADDRESS: "0.0.0.0:8080"
     BASE_URL: "https://searxng.example.abc/"
     IMAGE_PROXY: "false"
     METHOD: "POST"
     QUERY_IN_TITLE: "false"
     DEFAULT_THEME: "simple"
     SIMPLE_STYLE: "dark"
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
      - DAC_OVERRIDE
```
but none of the env works also i would love to set the simple dark theme as default,
i was using searx before and decided to use searxng.
if someone could explain me what i'm doing wrong and show me what i have to do to make my env settings to work it would be amazing !
thanks

**Comment by dalf** [comment]
It doesn't work because Searx(NG) supports environment configuration only on few variables. See https://github.com/searxng/searxng-docker/issues/8

You need to create a file in `/etc/searxng/settings.yml` with this content:
```yaml
use_default_settings: true
server:
  method: POST
  secret_key: "set a random value, if you don't the server won't stat"  # alternatively you can set SEARXNG_SECRET environment variable.
ui:
  query_in_title: true
  default_theme: simple
  theme_args:
    simple_style: dark
```

* `use_default_settings: true` will make sure to use the default configuration, the content above is only in addition to the existing configuration.
* Currently, SearXNG doesn't support `ENABLE_STATS: "false"` (it can be implemented in a safe way easily, if you need it, may I ask you to create an issue).
* There is no need for `BIND_ADDRESS: "0.0.0.0:8080"` or `PORT: "8080"`.
* `SAFE_SEARCH: "0"` is already the default.
* you don't need to mount `/etc/searx`.
