### ISSUE TITLE
Ideas for a new `settings.yml` format

### ISSUE THREAD

**Issue by not-my-profile** [searxng/searxng#681]
This issue serves to collect ideas for an improved `settings.yml` format (as suggested by @dalf in https://github.com/searxng/searxng/issues/631#issuecomment-999371016).

Ideas so far:

* change `engines` from a list to a mapping using `name` as the key (since it has to be unique)
* rename `engine` property to `module` (because it's confusing that engines have engines)
  Maybe even support `somepackage.somemodule` to load modules outside from `searx.engines`?
* support multiple `shortcuts` per engine (see https://github.com/searx/searx/issues/2229)
* require that `categories` must be a list (currently strings are automatically turned into lists)
* deprecate `proxies` for `network.proxies`
* change `safesearch` (bool) to `content_safety` (safe | unsafe | configurable)  #644

The new format could look like:

```yml
engines:
  yahoo:
    module: yahoo
    enabled_by_default: false  # currently, the default value is double negation "disable: false"
    shortcuts:
      - yh
      - ㄱ
    network:
      proxies:  # no need to specify all:// : ....
        - socks5://127.0.0.1:1337  # socks5 always means DNS resolution made by the proxy
        - socks5://127.0.0.1:1338
```

**Comment by dalf** [comment]
About the plugins (related to #759 )

```yaml
plugins:
  searx.plugins.self_info: 
    load: false
  searx.plugins.hash_plugin:
    enabled_by_default: false
    token: ['secret']  # enable with a token
  searx.plugins.hostname_replace:
    enabled_by_default: true
    config:  # configuration on this plugin (currently at the "root" of the document)
      '(.*\.)?youtube\.com$': 'invidious.example.com'
      '(.*\.)?youtu\.be$': 'invidious.example.com'
      '(.*\.)?youtube-noocookie\.com$': 'yotter.example.com'
      '(.*\.)?reddit\.com$': 'teddit.example.com'
      '(.*\.)?redd\.it$': 'teddit.example.com'
      '(www\.)?twitter\.com$': 'nitter.example.com'
      # to remove matching host names from result list, set value to false
      # 'spam\.example\.com': false
  mypackage.hostname_replace_extended:
    config:
      file: /a/file/some/where/on/the/file/system
```

There is only one plugin list:
* not to load internal plugin
* to provide plugin configurations
* to load external plugins
