### ISSUE TITLE
Engine without an about property raises an exception

### ISSUE THREAD

**Issue by return42** [searxng/searxng#732]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**

current master branch

**How did you install SearXNG?**

Add an engine without an about property to your `settings.yml` / e.g.:

```yaml
  - name: locate
    engine: command
    command: ['locate', '{{QUERY}}']
    shortcut: locate
    tokens: [ '123', '456' ]
    disabled: true
    delimiter:
        chars: ' '
        keys: ['line']
```

**What happened?**

    $ make run

Open preferences ..

```
Traceback (most recent call last):
  ...
  File "searxng/searx/webutils.py", line 162, in engine_sort_key
    return (engine.about.get('language', ''), engine.name)
AttributeError: module 'command' has no attribute 'about'
```

**Additional context**

@not-my-profile if you have time, could you please have a look about / thanks!
