### ISSUE TITLE
Engines without a category are not shown in the preferences

### ISSUE THREAD

**Issue by return42** [searxng/searxng#735]
EDIT: engines without category are added to categ `general` by default / see https://github.com/searxng/searxng/issues/735#issuecomment-1008869395

----

Engines without a category are not shown in the preferences

**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**

current master: `make run`

```yaml
  - name: locate
    # categories : [ 'it', 'files' ]
    engine: command
    command: ['locate', '{{QUERY}}']
    shortcut: locate
    # tokens: [ '123', '456' ]  # <-- remove or add the token 
    disabled: true
    delimiter:
        chars: ' '
        keys: ['line']
```

**Expected behavior**

~~Engines without a category are shown in the preferences in "search engines" --> "OTHER" --> "others"~~

**Additional context**

Another issue which might be related: set an empty category raises an exception:

```yaml
  - name: bing
    engine: bing
    shortcut: bi
    categories:
```

```
$ make run
...
Traceback (most recent call last):
...
  File "searx/engines/__init__.py", line 258, in is_engine_active
    if 'onions' in engine.categories and not settings['outgoing'].get('using_tor_proxy'):
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by return42** [comment]
@not-my-profile would you have a look about this issue? / .. otherwise I can do it.

**Comment by not-my-profile** [comment]
This bug was introduced by #729 which you just merged. (I currently don't have time to investigate further)

>Engines without a category are shown in the preferences in "search engines" --> "OTHER" --> "others"

Actually no, the default set in `searx/engines/__init__.py` is `"categories": ["general"]`.

**Comment by return42** [comment]
> This bug was introduced by #729 which you just merged. (I currently don't have time to investigate further)

Sorry my example was misleading / there was an token set that is why you think it is caused by #729 .. here is an better example:

```yaml
  - name: locate
    # categories : [ 'it', 'files' ]
    engine: command
    command: ['locate', '{{QUERY}}']
    shortcut: locate
    delimiter:
        chars: ' '
        keys: ['line']
```
