### ISSUE TITLE
RTL layout requires a few corrections

### ISSUE THREAD

**Issue by GreenLunar** [searxng/searxng#747]
**How To Reproduce**

Switch to Arabic, Persian or Hebrew

**Expected behavior**

1) Preferences link should be at the left side.
2) The send search button and search form are properly placed; It's only the frame shapes that need to be Flipped Horizontally.

**Screenshots & Logs**

![image](https://user-images.githubusercontent.com/2053884/149321887-987ee0a8-d877-4721-929a-7815cb7ca5f9.png)

**Comment by return42** [comment]
Thanks for opening an issue about RTL, we already had it on our project board / I also added this issue the board. I can't promise you when we have a solution.

**Comment by GreenLunar** [comment]
May you please refer me to the code responsible for the elements in question?
I can figure it out by myself.
Once I fix it, I'll send a PR.

**Comment by return42** [comment]
The theme itself is here https://github.com/searxng/searxng/tree/master/searx/static/themes/simple 

I don't expect it, but if it becomes needed to modify the template also, the sources are here https://github.com/searxng/searxng/tree/master/searx/templates/simple

@mrpaulblack and @dalf are more versed in less (CSS) then I.

EDIT: [Development Quickstart](https://docs.searxng.org/dev/quickstart.html)

**Comment by mrpaulblack** [comment]
Changes to make rtl work can go in here: https://github.com/searxng/searxng/blob/master/searx/static/themes/simple/src/less/style-rtl.less; Basically there are in the end 2 compiled min files: https://github.com/searxng/searxng/tree/master/searx/static/themes/simple/css

searxng-rtl.min.css contains all the CSS plus the changes made to the `style-rtl.less`

So you can basically just make the necessary changes to make the UI work on RTL in that file.

To work on themes:
* first clone and make your changes
* in root of git repo: `make themes.all` (this is going to install all depend. to make the themes)
* test with `make run`
* if you are done with your changes: `make static.build.restore` this is going to remove the build files so you can commit only the src changes in one commit
* after that commit: `make static.build.commit` (this is going to commit the changed build files)
* then just push the changes to a branch in your fork and you can do a PR :D

**Comment by dalf** [comment]
![image](https://user-images.githubusercontent.com/1594191/149387789-5c587adb-b3b6-4043-a0a4-b8e86bf60140.png)

See on the right side, you can see the source file : search.less line 142 for #send_search for example.

A first try 

searx/static/themes/simple/src/less/style-rtl.less :
```css
@import "style.less";

#q {
  border-radius: 0 10px 10px 0;
  border-right: inherit;
  border-left: none;
  padding-right: 12px !important;
  padding-left: 0 !important;
  direction: rtl;
}

#send_search {
  border-radius: 10px 0 0 10px;
  border-left: inherit;
  border-right: none;
}

#linkto_preferences {
  right: inherit;
  left: 10px
}

#backToTop {
  left: inherit;
  right: @results-width + @results-offset + (0.5 * @results-gap - 1.2em);
}

.category {
  margin-right: inherit;
  margin-left: 1rem;
}

.category label svg {
  padding-right: inherit;
  padding-left: .2rem;
}

.engines {
  float: left;
}

article[data-vim-selected] {
  border-left: inherit;
  border-right: 0.2rem solid var(--color-result-vim-arrow);
  border-radius: 10px 0 0 10px;
}
```

---

Perhaps some mixins would be helpful:

```less
.ltr-left(@offset) {
  left: @offset
}
```

And in `style-rtl.less` the mixins are overwritten (if doable): 

```less
.ltr-left(@offset) {
  right: @offset
}
```

It avoids this pattern:
```less
#backToTop {
  left: inherit; // reset to the default value
  right: @results-width + @results-offset + (0.5 * @results-gap - 1.2em); // copy paste from style.less
}
```
