### ISSUE TITLE
Use proxy button on result without morty

### ISSUE THREAD

**Issue by mrpaulblack** [searxng/searxng#857]
**Is your feature request related to a problem? Please describe.**
Since there is a ongoing effort to remove morty/filtron the proxy button for each result also gets lost with morty.

**Describe the solution you'd like**
Bring back the proxy button but instead of using morty just point to a defined proxy service.

**Describe alternatives you've considered**
Use morty only as a proxy for results.

**Additional context**
See: https://github.com/paulgoio/searxng/issues/23

**Comment by friedemannsommer** [comment]
I think this is a good idea, but how would that be accomplished? If the direct relation between Morty and SearXNG is removed what should the parameters for a (unknown) proxy look like? (Since `mortyurl` and `mortyhash` are rather specific)

To solve the HTTP parameter "problem", I can (currently) think of two solutions: "URL placeholders" or "Parameter mapping". There are probably other (and better) approaches and I would welcome a discussion about them.

<details>
<summary>Config examples</summary>

**Placeholder**:
```yaml
result_proxy:
  url: https://www.example.com/?url={URL}&hash={URL_HASH}
  key: !!binary "example"
  proxify_results: true
```

**Mapping**:
```yaml
result_proxy:
  url: https://www.example.com/
  key: !!binary "example"
  proxify_results: true
  proxy_parameters:
    url: "proxy_url_param"
    hash: "proxy_hash_param"
```
</details>

I would also prefer to have the option to use a separate proxy for images, instead of the integrated SearXNG proxy. This would allow to define a separate image proxy, just like a result proxy. (But this would require a separate `image_proxy` key)

<details>
<summary>Config examples</summary>

**Placeholder**:
```yaml
image_proxy:
  url: https://www.example.com/?url={URL}&hash={URL_HASH}
  key: !!binary "example"
```

**Mapping**:
```yaml
image_proxy:
  url: https://www.example.com/
  key: !!binary "example"
  proxy_parameters:
    url: "proxy_url_param"
    hash: "proxy_hash_param"
```
</details>
