### ISSUE TITLE
"ui.theme_args.results_on_new_tab" is not work.

### ISSUE THREAD

**Issue by chattytak** [searxng/searxng#987]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
2022.03.13-cd92a7ea 

**How did you install SearXNG?**
searxng-docker image

**What happened?**
I thought I edited `ui.theme_args.results_on_new_tab` in settings.yml to change the initial value, but it is not actually reflected.

**How To Reproduce**
Modify settings.yml.
```
...snip...
ui:
  ...snip...
  theme_args:
    # default style of oscar
    oscar_style: logicodev
    # style of simple theme: auto, light, dark
    simple_style: auto
    # Open result links in a new tab by default
    results_on_new_tab: true
...snip...
```

**Expected behavior**

results_on_new_tab is enabled.

**Screenshots & Logs**

**Additional context**
